### ISSUE TITLE
Add 'line-height' for text in image

### ISSUE THREAD

**Issue by joomla-ua** [JamesHeinrich/phpThumb#108]
Please add parameter for texts filters 'line-height' ;-)

**Comment by JamesHeinrich** [comment]
Untested, but I have added a 12th parameter to the "wmt" filter for line height scaling: https://github.com/JamesHeinrich/phpThumb/commit/cfbba13f1b97e32d7306d4c6d07f7a0b711f02ee
Please try it out and let me know if it doesn't work as expected (I don't have a phpThumb test platform set up right now).

**Comment by joomla-ua** [comment]
@JamesHeinrich all work!

Thank you for your nice php class!!!!
