### ISSUE TITLE
ImageMagick version isn't detected, but is installed.

### ISSUE THREAD

**Issue by Nordhbane** [JamesHeinrich/phpThumb#110]
I've ran into a problem where phpthumb is not detecting ImageMagick properly. I found someone with the same problem on Stackoverflow that describe the issue very well, but he wasn't getting any answers:

https://stackoverflow.com/questions/47989655/how-do-i-get-phpthumb-to-recognize-and-use-imagemagick-installation

I'm currently in the same boat with "ImageMagick 6.9.9-28 Q16 amd64 2018-01-02 http://www.imagemagick.org" with Image Magick Module version "3.4.3" and using phpThumb 1.7.15-201802181529. I can also run the script he provided to create an image with imagemagick to show that it works.

I unfortunately have no control over the installation of software on the server, so I can't updated ImageMagick to the latest version if that's required.

I have verified with the server provider that the installation path of Imagemagick is correct. On my phpThumb.demo.check.php it shows:
ImageMagick version: /usr/local/bin/convert [1] [1] [1] [1] [1] n/a
ImageMagick features: ImageMagick not found

Which seems to say that it can find the file, but it can't check it's version and thus it thinks it doesn't exist. If I alter the path to the file the 1's turn into 0's, so it feels like the path is not the issue here.

If there's any other information I can provide to help figure out the problem, please let me know.

**Comment by JamesHeinrich** [comment]
Are you able to run ```convert --version``` from the command line on your server? What is the complete output of that? It will typically be 3-6 lines or so starting with a line that starts with ```Version: ImageMagick```

**Comment by Nordhbane** [comment]
The problem is unfortunately that I don't have access to the command line on the server. The server provider does not allow this. I got that version number using phpinfo(), which I can give you access to if you want to take a closer look at the setup of the server.

**Comment by JamesHeinrich** [comment]
You could try
```
require_once('phpthumb.class.php');
$phpThumb = new phpThumb();
echo $phpThumb->ImageMagickVersion(true);
```

Also, note that the PHP ImageMagick extension that you see in phpinfo is not the same as the command-line version of ImageMagick.  The PHP extension didn't exist when I first wrote phpThumb, and it's not currently supported (it's on the todo list somewhere).

**Comment by Nordhbane** [comment]
The script didn't give me any outputs.

Ah, I see. Perhaps I'll just settle with GD2 in the meantime. Your git's doing wonders even without the ImageMagick-support. So my biggest appreciation for it.

**Comment by katillery** [comment]
Hi James,

Sorry if I'm being clueless, I'm having a similar issue, I've followed that ImageMagick needs to be installed for the command line, not just the php extension. I have both installed, yet when I run the "demo.check.php" it says:

ImageMagick version:	
/usr/bin/convert [1] [1] [1] [1] [1]
n/a

ImageMagick not found

This is the output of # convert --version:
Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

And # which convert:
/usr/bin/convert

php 7PHP Version 7.4.33
phpthumb 1.7.15-202004301145

**Comment by JamesHeinrich** [comment]
Possibly PHP doesn't have read or execute permissions to run ImageMagick, or the shell execution functions are disabled?

As a quick test, perhaps create a simple test PHP file with
```
echo `/usr/bin/convert --version`;
```
and see if you get any output?

**Comment by katillery** [comment]
I wrapped what you put in an "exec()" function, and this is the output:
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

If I run it as you provided it, it will just output "/usr/bin/convert --version", sorry if I'm missing something!

**Comment by JamesHeinrich** [comment]
Note that my example uses backticks not single-quotes.
https://www.php.net/manual/en/language.operators.execution.php

**Comment by katillery** [comment]
Sorry, that's above my pay grade! I've done it as requested now!

The output is:
Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org Copyright: (C) 1999-2021 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC Modules OpenMP(4.5) Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

**Comment by JamesHeinrich** [comment]
Interesting. It knows where `/user/bin/convert` is, and the exec functions appear to be working correctly, and yet it's not finding the version string.

Perhaps you can play with putting some temporary debugging output into the code block that attempts to parse the ImageMagick version and see where it's failing:
https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php#L1581-L1616
