### ISSUE TITLE
Question of usage

### ISSUE THREAD

**Issue by popkutt** [JamesHeinrich/phpThumb#112]
I apologize because this is not an issue with the code but rather my limited knowledge using it.

I need to take a square image, fit it on 1200w*628h white canvas, for posting in Facebook. I.e. add white bars to both sides. I managed to get that far on my own but the background is black instead of white:

http://www.nordoutlet.com/jama/crop/phpThumb.php?src=http://www.nordwatches.com/274793/michael-kors-armbandsur.jpg&h=630&w=1200&zc=0&fltr[]=crop|-300|-300|0|0]&fltr[]=size|1200|630|0]

What are the url parameters to make the bars white?

Thank you,

**Comment by JamesHeinrich** [comment]
The "far" (Force Aspect Ratio) and "bg" (BackGround color) parameters are what you need
http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x22
```
/phpThumb.php?src=<your filename>
&width=1200
&height=630
&far=1
&bg=FFFFFF
```
The above should be sufficient to resize the picture small enough to fit inside 1200x630 (in this case, your 1200x1200 source image resized to 630x630), then the canvas size forced to 1200x630 and the background filled with white (hex color FFFFFF).

**Comment by popkutt** [comment]
Great! Thank you so much!

**Comment by JamesHeinrich** [comment]
@popkutt: I just noticed you're using a 7-year-old version of phpThumb, you really should upgrade as there are security issues with older versions.

**Comment by popkutt** [comment]
Thank you,


upgraded, it works great.

However, I got an issue with some filenames containing symbol '+', possibly
some other symbols also:

This one works:
https://www.nordoutlet.com/jama/crop_new/phpThumb.php?src=https://m.media-amazon.com/images/I/81W--zcBOkL.jpg
This doesn't:
https://www.nordoutlet.com/jama/crop_new/phpThumb.php?src=https://m.media-amazon.com/images/I/81EK8FlZW+L.jpg

Is there any way to bypass the issue? I usually process 1000-3000 images in
one go, takes some time to manually fix all those.

Also, is there a way to replace the blue error message image with something
else (the images are uploaded into a live web store), like my logo?

Thank you for the script,




Elvis Nigol
www.nordoutlet.com

**Comment by JamesHeinrich** [comment]
The '+' character is a [special URI character](https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters) and needs to be encoded. In reality, as a matter of good form and to prevent unexpected behavior, _all_ parameters passed to phpThumb.php (or, indeed, any URL with parameters) should be URL-encoded using the [PHP function rawurlencode](http://us3.php.net/manual/en/function.rawurlencode.php).
So you should have something equivalent to:
```
$URL = 'https://www.nordoutlet.com/jama/crop_new/phpThumb.php?src=' . rawurlencode('https://m.media-amazon.com/images/I/81EK8FlZW+L.jpg');
```

As for a generic error image, see `$PHPTHUMB_CONFIG['error_message_image_default']` in [phpThumb.config.php](https://github.com/JamesHeinrich/phpThumb/blob/master/phpThumb.config.php.default#L159) (or `$phpThumb->config_error_message_image_default` in [phpthumb.class.php](https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php#L87) if running in object mode).
