### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by maulikdalsaniya** [JamesHeinrich/phpThumb#114]
secondhandgraphics.com/main/phpThumb.php?src=http://secondhandgraphics.com/usrfiles/thumbs/palladio.jpg&w=300&h=200&zc=T&aoe=1 :- This is working fine

http://www.secondhandgraphics.com/main/phpThumb.php?src=http://secondhandgraphics.com/usrfiles/thumbs/palladio.jpg&w=300&h=200&zc=T&aoe=1 -: This is not working

I have add www. in the url now working image.

Please help me.

**Comment by JamesHeinrich** [comment]
1) You're using a 4-year-old version of phpThumb, you really should upgrade.

2) You're making unnecessary calls to retrieve the source image over HTTP, this slows things down tremendously and can introduce problems (in your case, likely related to cross-domain privileges not being set up correctly). Just call the source image locally and it will work fine with or without www
http://www.secondhandgraphics.com/main/phpThumb.php?src=/usrfiles/thumbs/palladio.jpg&w=300&h=200&zc=T&aoe=1

**Comment by maulikdalsaniya** [comment]
Thanks.
