### ISSUE TITLE
BUG  Notice: A non well formed numeric value encountered in /home/sysrural1/public_html/controlpanel/classes/phpThumbNew/phpthumb.class.php on line 4359

### ISSUE THREAD

**Issue by franciscocsysteames** [JamesHeinrich/phpThumb#115]
Notice: A non well formed numeric value encountered in /home/sysrural1/public_html/controlpanel/classes/phpThumbNew/phpthumb.class.php on line 4359

**Comment by JamesHeinrich** [comment]
First question: are you using the latest version such that your line 4359 is the same one I'm looking at?
https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php#L4359

If so, can you throw in some debugging just before that line to see which of the 8 variables is non-well-formed?
`var_dump($dstX); var_dump($dstY); var_dump($srcX); var_dump($srcY); var_dump($dstW); var_dump($dstH); var_dump($srcW); var_dump($srcH);`

**Comment by franciscocsysteames** [comment]
Yes I have had the last version. So I solved the problem by removed the "show errors" on my phpinit file

**Comment by JamesHeinrich** [comment]
Well no, that doesn't solve the problem, it just hides the error message.
But if you can't provide debugging info, I can't fix it.

Closing issue until OP provides more info.
