### ISSUE TITLE
Decode problems with hight security enabled

### ISSUE THREAD

**Issue by Jessica2710** [JamesHeinrich/phpThumb#118]
Hi! 
i use the high_security_enabled=true and it's fine !
but the img tag has the attribute src set to **"include/resize/phpThumb.php?src=..%2F..%2Fimages%2Fprodotti%2F2694-10-padella%20prodiamond%20tognana%2024%20cm.jpg&q=50&sia=6-10-ef23c1ddd865f61cc8bd792df664414b.jpg&w=600&h=450&far=C&bg=FFFFFF&hash=6f60ce715d0b2796a703fcbf28f88a20"**
I wish it could be src=**"include/resize/phpThumb.php?src=../../images/prodotti/2694-10-padella prodiamond tognana 24 cm.jpg&q=50&sia=6-10-ef23c1ddd865f61cc8bd792df664414b.jpg&w=600&h=450&far=C&bg=FFFFFF&hash=6f60ce715d0b2796a703fcbf28f88a20"**
i try every type of encode and decode function in php but nothing work
Thanks!

**Comment by Jessica2710** [comment]
I can't show an example page beacause it's a new project. this is the function that returns the image's url 

`
function resizeImage($pathIncludeResized,$pathImage,$Image,$W,$H,$ALIGN,$BG_Image){
	 require_once('resize/phpThumb.config.php');
	$res="src=".$pathImage.$Image."&q=50&sia=".$Image."&w=".$W."&h=".$H."&far=".$ALIGN."&bg=".$BG_Image;
	$resized_url= htmlspecialchars(phpThumbURL($res, 'include/resize/phpThumb.php'));
	return $resized_url;
}
`

**Comment by JamesHeinrich** [comment]
Your first example has the source filename correctly URLencoded, with spaces replaced with `%20` and slashes replaced with `%2F`
Why is this a problem?

**Comment by Jessica2710** [comment]
I want to keep the original filename without %20 because of SEO rules.
If i disable the hight security the filename is the original filename without %20 or %2F.
Is it possible with hight security enabled ?
Thanks

**Comment by JamesHeinrich** [comment]
Technically no, you can't specify the filename with actual spaces. Modern browsers will silently correct your mistake and make it work, but it's still in violation of [RFC-3986](https://tools.ietf.org/html/rfc3986).
It is acceptable to encode the space character as either `%20` or `+`, so if it looks better to you then you can encode it that way, but no self-respecting search engine will have any problem correctly urldecoding the URL.
If you want more search-friendly URLs, you should set up some rewrite rules in .htaccess and structure your img src something like
`/image/600/400/prodotti%2f2694-10-padella+prodiamond+tognana+24+cm.jpg`
and let the rewrite rule take care of passing all the ugly parameters to phpThumb.
