### ISSUE TITLE
Fatal error: Call to undefined function URLschemeDefaultPort()

### ISSUE THREAD

**Issue by badbadmonkey** [JamesHeinrich/phpThumb#119]
I've installed the package as downloaded from GH (current version: v1.7.15-201806071234), added only the high security password to phpThumb.config.php and made no other changes, and I get the following PHP error:

`Fatal error: Call to undefined function URLschemeDefaultPort() in /home3/peters/public_html/include/phpThumb-master/phpthumb.functions.php on line 748`

I'm running an older version of phpThumb without issue, but can't figure this problem. It's generated just from phpThumb.demo.check.php so I'm eliminating any extraneous factors.

**Comment by JamesHeinrich** [comment]
Thanks. It got broken in https://github.com/JamesHeinrich/phpThumb/commit/bb3ecb6ba34e3fb7130cfb0f6bdc04a37f544c81 and has been fixed in https://github.com/JamesHeinrich/phpThumb/commit/1fc28a6acf1ffa5ad60a57ee1304fd580892c990
