### ISSUE TITLE
Notice: Undefined variable: scheme in phpthumb.functions.php on line 748

### ISSUE THREAD

**Issue by badbadmonkey** [JamesHeinrich/phpThumb#120]
James thanks for fixing the last one, I'm trying again and this error comes from the same section.

Notice: Undefined variable: scheme in /home3/peters/public_html/include/phpthumb-master/phpthumb.functions.php on line 748

At least phpThumb.demo.check.php runs ok this time, but images aren't generated of course.

**Comment by JamesHeinrich** [comment]
Sorry, should be fixed in https://github.com/JamesHeinrich/phpThumb/commit/8159c543fbaf407b618c41c3018423b9395dde55
(I'm fixing these blind, I'm not currently able to test, sorry).
