### ISSUE TITLE
PHPThumb needs syntax update

### ISSUE THREAD

**Issue by sashabeep** [JamesHeinrich/phpThumb#145]
Using php 7.4.1

1× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.functions.php:219
-- | --
2× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.functions.php:1019
3× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:585
1× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1438
2× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1278
1× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1271
2× | PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in .../snippets/phpthumb/phpthumb.class.php:1261

**Comment by opengeek** [comment]
Pull requests #146 and #147 address these issues of using array and string offset access with curly braces syntax. @JamesHeinrich, can we please get this merged and a release out? This is way overdue considering 7.4 has been released for quite a while now.

**Comment by JamesHeinrich** [comment]
Pull requests 146/147 have been merged (sorry, I was on vacation until today with no internet access).
