### ISSUE TITLE
Magic quotes is deprecated in php 7.4.2

### ISSUE THREAD

**Issue by sashabeep** [JamesHeinrich/phpThumb#149]
Getting error caused by function call
```
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/.../phpThumb/phpThumb.php on line 222
**Headers already sent in file "/home/.../phpThumb/phpThumb.php" on line "222", dumping error message as text:**
```

phpThumb.php on line 222
```php
if (get_magic_quotes_gpc()) {
	// deprecated: 'err', 'file', 'goto',
	$RequestVarsToStripSlashes = array('src', 'wmf', 'down');
	foreach ($RequestVarsToStripSlashes as $key) {
		if (isset($_GET[$key])) {
			if (is_string($_GET[$key])) {
				$_GET[$key] = stripslashes($_GET[$key]);
			} else {
				unset($_GET[$key]);
			}
		}
	}
}
```

removing or commenting this condition solves the error

**Comment by JamesHeinrich** [comment]
Should be fixed in https://github.com/JamesHeinrich/phpThumb/commit/180c7520d6d85aa7c528d71de33d17408e915e88

**Comment by samuelhgf** [comment]
@JamesHeinrich still not working

**Comment by JamesHeinrich** [comment]
Please explain further what you mean by "not working"?
What version of PHP are you testing with? What output or error do you get?

**Comment by samuelhgf** [comment]
I am using 7.4.3
Getting this `Function get_magic_quotes_gpc() is deprecated`

**Comment by sashabeep** [comment]
@samuelhgf looks like you didn't updated the script

**Comment by samuelhgf** [comment]
I downloaded the latest version from here https://sourceforge.net/projects/phpthumb/files/phpThumb%28%29/

**Comment by JamesHeinrich** [comment]
The SourceForge archive hasn't been updated since 2014 (although I will push the v1.7.15 release there now).
The most recent version is always available at https://github.com/JamesHeinrich/phpThumb/archive/master.zip

**Comment by samuelhgf** [comment]
Thank you!
There is a doc about how to use phpThumb as composer package? More specific with Laravel?

**Comment by samuelhgf** [comment]
@JamesHeinrich

**Comment by JamesHeinrich** [comment]
I don't have any such documentation (nor knowledge).
