### ISSUE TITLE
PHP 7.4-compatible release needed

### ISSUE THREAD

**Issue by opengeek** [JamesHeinrich/phpThumb#152]
PHP 7.4 was officially released on November 28, 2019. Several issues in phpThumb dealing with deprecated features in 7.4 were fixed recently, yet there is still no stable release of phpThumb that includes these changes. That makes it very difficult to support 7.4 in any product that uses phpThumb as a dependency. Can we please get a stable release with these changes included?

**Comment by JamesHeinrich** [comment]
Sorry, didn't realize it hadn't been so long(!) since the last tagged release.
https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.15
