### ISSUE TITLE
Which LICENSE is phpThumb?

### ISSUE THREAD

**Issue by arturmamedov** [JamesHeinrich/phpThumb#159]
What about license of phpThumb?

**Comment by JamesHeinrich** [comment]
GPL2: https://github.com/JamesHeinrich/phpThumb/blob/master/docs/phpthumb.license.txt

It could potentially be released under additional licences if someone has particular need of such.

**Comment by arturmamedov** [comment]
NO sorry again, it also say:

```
that you can change the software or use pieces of it
in new free programs; and that you know you can do these things.
```

So i can make fork and change code for me, and use it, maybe make pull request's.

**Comment by arturmamedov** [comment]
And why not create a LICENSE.md for immediately see it on GitHub?

**Comment by JamesHeinrich** [comment]
/license.txt added and license texts added in https://github.com/JamesHeinrich/phpThumb/commit/bc0fa33aa4b825cbafef8584a9bee888c8d75e5f
