### ISSUE TITLE
Focal system for croppe

### ISSUE THREAD

**Issue by micker** [JamesHeinrich/phpThumb#160]
Hello i didn't found how but did we have a param to choose focal position for croppe ?
Like top left, top center, top right, middle left .... 
Thanks to all

**Comment by JamesHeinrich** [comment]
See "Parameters" section of [Readme.txt](https://github.com/JamesHeinrich/phpThumb/blob/master/docs/phpthumb.readme.txt)

For Zoom-Crop (&zc) with the right parameter you can point it towards any of the 4 sides, 4 corners, or middle.
Cropping from a source area is specified by pixels, as is the crop filter.

**Comment by micker** [comment]
thanks
