### ISSUE TITLE
Allow to create output in webp

### ISSUE THREAD

**Issue by micker** [JamesHeinrich/phpThumb#163]
hello it possible to convert any image in webp in fly ?

**Comment by DenysNosov** [comment]
> hello it possible to convert any image in webp in fly ?

Yes!

**Comment by micker** [comment]
sorry can you explain more where i can find it

**Comment by micker** [comment]
I didnt find it in documentation...

**Comment by JamesHeinrich** [comment]
If you're trying to output in webp format (and your server supports doing so) setting the output format to `webp` (e.g. `&f=webp`) should be all that's needed.
I added the missing formats to the documentation in https://github.com/JamesHeinrich/phpThumb/commit/d1ca56cf26d57f42484191dba1d55d65867eb789

**Comment by micker** [comment]
thanks !

**Comment by badbadmonkey** [comment]
James, how does one control the quality in Webp or other lossy formats like AVIF, is the q factor used same as JPEG?

Equally, how does one specify generation of lossless Webp etc? Is it q=100? If so this makes it a 'special' number, different to q=100 in JPEG.

Anyway whatever the answer it should be clear in the docs.
