### ISSUE TITLE
Release with PHP 8 compatibility fixes?

### ISSUE THREAD

**Issue by opengeek** [JamesHeinrich/phpThumb#170]
Can we please get a release with PHP 8 compatibility fixes? This version of PHP has been out for well over two months and any project using phpThumb as a dependency cannot move forward until there is a stable release of this project.

**Comment by JamesHeinrich** [comment]
v1.7.16-202012161640
https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.16

**Comment by JoshuaLuckers** [comment]
Thanks a lot 🙏
