### ISSUE TITLE
[Bug Fixed] function readfile in many host website is disabled

### ISSUE THREAD

**Issue by aldoexpert** [JamesHeinrich/phpThumb#173]
Dear @JamesHeinrich ,

I see on your change log is used **readfile** for showing cached/rendered image (v1.5.3 - May 4, 2005)
but in many website share host is disabled that function for reason security
so if **readfile** change to **echo file_get_contents** this library work perfectly in website host (I has been tested it)

Note:
**readfile** function only used in phpThumb.php

Thanks if you update your code

**Comment by JamesHeinrich** [comment]
Changed in https://github.com/JamesHeinrich/phpThumb/commit/14211001b499086a4c348e8718c2c9e484489e7d
