### ISSUE TITLE
phpThumb in MAMP Environment

### ISSUE THREAD

**Issue by brandonflatsoda** [JamesHeinrich/phpThumb#174]
Is it possible to get phpThumb to recognize ImageMagick in a mamp environment. I enabled the extension and can see it being available in phpinfo(). But for the demo check the ImageMagick Version always shows [0] [0] [0] [0] [0] n/a.

**Comment by JamesHeinrich** [comment]
phpThumb predates the availability of the ImageMagick extension, it relies on calling the command-line executable as specified in $PHPTHUMB_CONFIG['imagemagick_path']

**Comment by brandonflatsoda** [comment]
Yep! After multiple hours I I think that I'm almost there, and I've found the path for the executable, but placing "/usr/local/Cellar/imagemagick/7.0.10-53_1/bin/magick" in the 'imagemagick_path' still leaves it as unrecognized.
