### ISSUE TITLE
fopen() fails when using remote images from SSL

### ISSUE THREAD

**Issue by ghost** [JamesHeinrich/phpThumb#18]
Since Flickr has changed over to SSL access only all my images have broken on my site. Any image that comes from a non-SSL site renders just fine, but not at all from SSL sites. I have tracked this down to phpThumb's use of fopen() to grab the data stream. fopen() cannot handle "https"!

Here is a partial debug message:

Error opening "https://farm9.staticflickr.com:443/8401/8641054896_c831d16923_o.jpg"

**Comment by touqeer-wal** [comment]
I'm getting the same problem the above solution not worked for me.

**Comment by Georgi-Todorov** [comment]
I believe this is still part of issue 39 (https://github.com/JamesHeinrich/phpThumb/issues/39), which is marked as closed, but I think it's still an issue.

@ghost can you try something that may help you with this issue?

In the same file duplicate line 759, and comment out the original one.

### $rawData = self::URLreadFsock(@$parsed_url[ 'host'], @$parsed_url[ 'path'].'?'.@$parsed_url[ 'query'], $errstr, true, (@$parsed_url[ 'port'] ? @$parsed_url[ 'port'] : 80), $timeout);

Change the duplicated line - remove the port piece and leave just two quotes like this:
$rawData = self::URLreadFsock(@$parsed_url[ 'host'], @$parsed_url[ 'path'].'?'.@$parsed_url[ 'query'], $errstr, true, **''**, $timeout);

This should allow following the HTTP to HTTPS redirects or any other combination.

I see where James is coming from and why he implemented it that way. But in day to day requests, websites rarely use explicitly defined port in the URL. Fopen should be able to handle the connection based on the protocol.

I extracted the fopen function from that functions file in a separate file and tested it out. It works just fine.
cURL though should be able to handle this without any issues. Curious why it didn't work either.

**Comment by JamesHeinrich** [comment]
I have made some changes to URL parsing and URLreadFsock, let me know if it still gives problems.
https://github.com/JamesHeinrich/phpThumb/commit/bb3ecb6ba34e3fb7130cfb0f6bdc04a37f544c81
