### ISSUE TITLE
PHP 8.0 warning: Deprecated: Required parameter $phpThumbObject follows optional parameter $rotate_angle 

### ISSUE THREAD

**Issue by Mark-H** [JamesHeinrich/phpThumb#184]
Didn't see an issue for this yet, but on PHP 8.0 the following message gets logged:

```
PHP Deprecated:  Required parameter $phpThumbObject follows optional parameter $rotate_angle 
in vendor/james-heinrich/phpthumb/phpthumb.filters.php on line 755
```

See: https://php.watch/versions/8.0/deprecate-required-param-after-optional

There may be more similar issues; I just stumbled across this one in my logs and figured I'd make sure it was reported. :)

**Comment by ggppdk** [comment]
This was fixed with: f1f6cd6
