### ISSUE TITLE
Unable to display image with PHP 8.1. 

### ISSUE THREAD

**Issue by yepkoo** [JamesHeinrich/phpThumb#187]
Hi

Unable to display image with PHP 8.1. 
There are some deprecated coding changes.
Can we expect an update soon? 

For now, I have removed the codes that cause the error, but it seems that there will be other problems in the future. 

Thank you

**Comment by sks1024** [comment]
@yepkoo Can you share the files you have made these changes in so I can use them?

**Comment by yepkoo** [comment]
You can download the attachment.
In PHP 8, if you use php ready functions without querying whether some values are null or not, it gives an error.

[thumb.zip](https://github.com/JamesHeinrich/phpThumb/files/8921335/thumb.zip)

**Comment by JamesHeinrich** [comment]
> You can download the attachment. In PHP 8, if you use php ready functions without querying whether some values are null or not, it gives an error.

@yepkoo Would you mind posting what changes you actually made against the current versions of `phpthumb.class.php` and `phpthumb.functions.php` ?  A PR would be ideal, a diff would suffice, to make it easy for me to integrate your fixes.

**Comment by yepkoo** [comment]
@JamesHeinrich 
I found a site called text-compare.com.
I think the results are correct.
I have attached the changes I made as a picture.
![001](https://user-images.githubusercontent.com/56581931/174165114-455bcd03-aa8a-4785-a66b-54ffd8001aa3.png)
![002](https://user-images.githubusercontent.com/56581931/174165123-f8330a04-70da-4660-8d63-f6c9984a2cd1.png)
![003](https://user-images.githubusercontent.com/56581931/174165127-047edcc3-8377-4ee1-ae8c-db0eea16ca42.png)
![004](https://user-images.githubusercontent.com/56581931/174165130-68bf2af8-3154-4577-b637-c5756d6beb4c.png)
![005](https://user-images.githubusercontent.com/56581931/174165134-a21a7c1b-4d9b-49a5-b5b9-49a5586f9898.png)
![006](https://user-images.githubusercontent.com/56581931/174165136-c5b7f844-d8ca-4b43-b084-e9441cd67ea2.png)

**Comment by JamesHeinrich** [comment]
Some of those are no longer applicable in the current development version, the others I have changed in https://github.com/JamesHeinrich/phpThumb/commit/76e13e90a70f7762bfebec6cfa8266290542c4fd

**Comment by eddstep** [comment]
Hi, @JamesHeinrich . I have updated, but still is error with 
`PHP Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/mlibrary.local/frameworks/yii2/vendor/james-heinrich/phpthumb/phpthumb.class.php on line 1472
PHP Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/mlibrary.local/frameworks/yii2/vendor/james-heinrich/phpthumb/phpthumb.class.php on line 1472
PHP Deprecated: is_file(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/mlibrary.local/frameworks/yii2/vendor/james-heinrich/phpthumb/phpthumb.class.php on line 1474
PHP Deprecated: is_file(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/mlibrary.local/frameworks/yii2/vendor/james-heinrich/phpthumb/phpthumb.class.php on line 1474
PHP Deprecated: is_executable(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/mlibrary.local/frameworks/yii2/vendor/james-heinrich/phpthumb/phpthumb.class.php on line 1475
PHP Deprecated: is_executable(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/mlibrary.local/frameworks/yii2/vendor/james-heinrich/phpthumb/phpthumb.class.php on line 1475
`

**Comment by JamesHeinrich** [comment]
https://github.com/JamesHeinrich/phpThumb/commit/4d954f469a13ae6d0417f549faadd76a79ee7356 should hopefully fix those, let me know if you find others.

**Comment by sks1024** [comment]
I think @yepkoo fixed phpthumb.functions.php as well.  With the current version the script doesn't work.  With his version it does.

**Comment by JamesHeinrich** [comment]
Try again with https://github.com/JamesHeinrich/phpThumb/commit/c74b2e38dd04f147f09b176d2666565d59293e30 ?

**Comment by sks1024** [comment]
Looks good from here.  Working with newest revisions.  Thanks,
