### ISSUE TITLE
invalid hash

### ISSUE THREAD

**Issue by mephitrpg** [JamesHeinrich/phpThumb#19]
some images returns HTTP 403 cause of "invalid hash" http://www.ciboiswhat.com/en/home.php/
i'm using phpThumb 1.7.13

**Comment by dalefish** [comment]
Quick note: ensure you turn off debug mode after implementing changes so you don't spend ages trying to find an error message that isn't there.

**Comment by audiocommander** [comment]
I just wanted to add that it's not just spaces, it's any kind of special character in filenames that's producing this 403 issue with high_security_enabled, e.g. äöüß (frequently used in german).

Thanks to mephitrpg, using a rawurlencode() on the src param fixes this indeed.

**Comment by JamesHeinrich** [comment]
What do you guys think of phpThumbURL automatically rawurlencode()'ing the parameters passed, like this:

```function phpThumbURL($ParameterString, $path_to_phpThumb='phpThumb.php') {
	global $PHPTHUMB_CONFIG;
	$ParamterStringEncodedArray = array();
	foreach (explode($PHPTHUMB_CONFIG['high_security_url_separator'], $ParameterString) as $key_value_pair) {
		@list($key, $value) = explode('=', $key_value_pair);
		$ParamterStringEncodedArray[] = $key.'='.rawurlencode($value);
	}
	$ParameterString = implode($PHPTHUMB_CONFIG['high_security_url_separator'], $ParamterStringEncodedArray);
	return $path_to_phpThumb.'?'.$ParameterString.$PHPTHUMB_CONFIG['high_security_url_separator'].'hash='.md5($ParameterString.$PHPTHUMB_CONFIG['high_security_password']);
}```

**Comment by audiocommander** [comment]
hmm, not sure. I think it would suffice and be probably slightly more efficient to just update the commented example in phpThumb.config.php:249 from:

    echo '<img src="'.htmlspecialchars(phpThumbURL('src=/images/pic.jpg&w=50', '/phpThumb/phpThumb.php')).'">';

to:

    echo '<img src="'.htmlspecialchars(phpThumbURL('src='.rawurlencode('/images/pic.jpg').'&w=50', '/phpThumb/phpThumb.php')).'">';

...or having a slightly more abstract function for building the parameters and calculating the hash.
