### ISSUE TITLE
Feature request: AVIF support

### ISSUE THREAD

**Issue by leonie12** [JamesHeinrich/phpThumb#190]
AVIF image format support has landed in PHP 8.1, brings drastic file size reductions and is supported by more and more browsers.
Would be great if AVIF would be supported by phpThumb in nearer future :-) . Are there plans to include AVIF support?

**Comment by JamesHeinrich** [comment]
Untested support added in https://github.com/JamesHeinrich/phpThumb/commit/7240f8950a3bf1266cb4f46597631bdcbe4497b3
Let me know if something doesn't work as expected.
