### ISSUE TITLE
not defined IMAGETYPE_AVIF on php8 or lower

### ISSUE THREAD

**Issue by bskade** [JamesHeinrich/phpThumb#191]
I think adding code below
in phpthumb.class.php after line 56
was intented (like for $predefined_IMG_constants), but forgotten
```
foreach ($predefined_IMAGETYPE_constants as $PHP_constant_name => $PHP_constant_value) {
	if (!defined($PHP_constant_name)) {
		define($PHP_constant_name, $PHP_constant_value);
	}
}
```

**Comment by Mark-H** [comment]
Hi @JamesHeinrich, could you tag a release with this fix so the update becomes available through composer? Just ran into this issue with `1.7.18-202208061319` and was about to send a PR when I realised it had already been fixed. :)

**Comment by JamesHeinrich** [comment]
https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.19

**Comment by Mark-H** [comment]
Thank you 💙
