### ISSUE TITLE
cropping does not work correctly

### ISSUE THREAD

**Issue by otterman71** [JamesHeinrich/phpThumb#20]
Hi,

for example i have an image with 2000x545 and i want an image with the dimension 384x230. I use focal points, so i have to set sx=544, sy=0, sw=910 and sh=545.

But the result is an blank image (1x1)

If i use sx=0 i got an image with 384x105. if i use the far parameter i got the same dimension.
only without the sx,sy,sw and sh anf far=1 i got the image width i want.

do i something wrong? 

Helge

**Comment by arturmamedov** [comment]
@JamesHeinrich maybe can we close issues that are to old? < 2017 or < 2018
