### ISSUE TITLE
Control quality for webp etc

### ISSUE THREAD

**Issue by badbadmonkey** [JamesHeinrich/phpThumb#204]
1. How does one control the quality in Webp or other lossy formats like AVIF, is the q factor used same as JPEG?

I am testing this and I get webp's of the same size regardless of how q is set, so I presume it's ignored atm. If I'm wrong please advise.
They are also quite large so must be defaulting to a fairly high quality.

2. Equally, we need a way to specify generation of lossless Webp etc. vs lossy.
q=100 ?

**Comment by honzito** [comment]
WEBP Quality parameter q=1-100 now works in GD backend and also in ImageMagick backend ($PHPTHUMB_CONFIG['prefer_imagemagick'] = true;)
BTW: The quality parameter is in ImageMagic supported from v 7.0.8-68, which (in most cases) is not yet on the server.

see https://github.com/JamesHeinrich/phpThumb/pull/211#issue-1717476776

**Comment by badbadmonkey** [comment]
Is q=100 lossless?

**Comment by badbadmonkey** [comment]
Thank you honzito. I got webp q working.

What about AVIF ?
