### ISSUE TITLE
Maybe the very last curly brace error in source

### ISSUE THREAD

**Issue by gnanet** [JamesHeinrich/phpThumb#219]
https://github.com/JamesHeinrich/phpThumb/blob/7ee966b38ddd7eb4d8091389aa514604710711c8/demo/phpThumb.demo.gallery.php#L64

```diff
- if (is_dir($currentdir.'/'.$file) && ($file{0} != '.')) {
+ if (is_dir($currentdir.'/'.$file) && ($file[0] != '.')) {
```

stumbled upon while moving some of my galleries to a new server,and done a php8.1 lint on all my php sources

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/phpThumb/commit/98d876606c09d42bf48a3c8022871fabb7cea46b thanks
