### ISSUE TITLE
default quality does not work on imagepng

### ISSUE THREAD

**Issue by happit-jannes** [JamesHeinrich/phpThumb#223]
phpthumb.class.png:1099
```
$this->thumbnailQuality = max(1, min(99, ($this->q ? (int) $this->q : 75)));
```
Later this is called:
```
					$ImageOutFunction = 'image'.$this->thumbnailFormat;
					if (!function_exists($ImageOutFunction)) {
						$this->DebugMessage($ImageOutFunction.' is not available', __FILE__, __LINE__);
						return false;
					}
					header('Content-Type: '.phpthumb_functions::ImageTypeToMIMEtype($this->thumbnailFormat));
					if ($this->thumbnailFormat == 'gif') {
						@$ImageOutFunction($this->gdimg_output);
					} else {
						@$ImageOutFunction($this->gdimg_output, null, $this->thumbnailQuality);
					}
```

So if `$ImageOutFunction` is set to `imagepng`, and `q` parameter is not set, then it will try to run `imagepng(..., 75)`, which causes an error and no output.

`imagepng` takes 0-9 as compression level
https://www.php.net/manual/en/function.imagepng

`imagejpeg` takes 0-100 as image quality
https://www.php.net/manual/en/function.imagejpeg

Fix: set the default to -1 instead of 75 (read docs, -1 seems to be close to 75)

**Comment by JamesHeinrich** [comment]
Hopefully fixed in https://github.com/JamesHeinrich/phpThumb/commit/951a2f1adc42bed23849fa0d4c90b2cbb9831e39
