### ISSUE TITLE
escapeshellarg() on shared hosts

### ISSUE THREAD

**Issue by TimGS** [JamesHeinrich/phpThumb#25]
Some shared hosts disable escapeshellarg(). Whilst the resulting failure of phpThumb to run is not a bug, it would help those using such hosts if instead, we had something like:

```php
function _escapeshellarg($input) {
    $input = str_replace('\'', '\\\'', $input);
    return '\'' . $input . '\'';
}
```

...and then replacing all instances of escapeshellarg with _escapeshellarg.

This solution could probably be improved upon - maybe by detecting if escapeshellarg is actually disabled before using the substitute.

-- Tim.

**Comment by JamesHeinrich** [comment]
Fixed in https://github.com/JamesHeinrich/phpThumb/commit/b54fbc36a3b71c7039a01875834c32245d5d24df

**Comment by TimGS** [comment]
Thanks.
