### ISSUE TITLE
Interlace with GenerateThumbnail

### ISSUE THREAD

**Issue by TeckniX** [JamesHeinrich/phpThumb#26]
Just trying to understand why GenerateThumbnail doesn't include the interlace option, while OutputThumbnail does?

**Comment by JamesHeinrich** [comment]
The interlace setting only has relevance when outputting the image to a file format, whether a progressive JPEG or interlaced GIF. It is irrelevant to the actual GD thumbnail image prepared by GenerateThumbnail.
http://www.php.net/manual/en/function.imageinterlace.php

**Comment by TeckniX** [comment]
You're right, I should've looked more closely - RenderOutput is really the function that should have the Interlace option, yet I don't see it?

**Comment by JamesHeinrich** [comment]
You're right, it should be in both RenderOutput() and OutputThumbnail().
Fixed in https://github.com/JamesHeinrich/phpThumb/commit/93c52ae483e92e5f02a0314b12d20d12d65cdaef

**Comment by TeckniX** [comment]
Awesome! Thanks for the quick-fix :) :+1:
