### ISSUE TITLE
sourceFilename getting lost

### ISSUE THREAD

**Issue by Sandman83** [JamesHeinrich/phpThumb#33]
Hi! 
I discovered a strange behavior which occurs in my case trying uploading some pictures using the library. The debug output is: 

```
phpThumb() v1.7.14-201507071049
http://phpthumb.sourceforge.net

"" does not exist
Debug timer info
Message	Start Time (ms)	End Time (ms)	Duration (ms)
Core Processing (Derived)	0	53	53
Component initialization and startup	53	56	4
Controller action	56	66	0
Debug timer info
Message	Start Time (ms)	End Time (ms)	Duration (ms)
Core Processing (Derived)	0	-1.44026294042E+12	-1.44026294042E+12
Component initialization and startup	53	56	4
Controller action	56	66	0
```

I spent some time debugging it by myself, so I want to share, what I found out. At the end, this is not a real bug of the code but something which definitely needs a workaround. 

Chasing the stack down the called functions in phpthumb,class.php I got to
```
ResolveSource()
ResolveFilenameToAbsolute($filename)
```
and then somewhere around line 1283 to the line
```
$AbsoluteFilename = $this->resolvePath($AbsoluteFilename, $this->config_additional_allowed_dirs);
```
which is called unconditionally and sets $AbsoluteFilename to an empty string

In the resolvePath function I do not go beyond the first if-else block, which uses the realpath. The idea is obvious but as I use a shared server my php scripts do not own all the needed file permissions which are needed for the function realpath as stated here: 
http://php.net/manual/en/function.realpath.php
In particular, my scripts do not have executable permissions for the folders upwards from my home folder on the server, which are needed for the correct work of the realpath function. 

So the "bug" is somewhat strange in the sense, that there are no errors in the code. But as shared servers are common in my surroundings I expect to encounter this problem wherever I would use the library. 

Could you help me with that problem?

**Comment by JamesHeinrich** [comment]
I have added a workaround for realpath not being available in your server configuration:
https://github.com/JamesHeinrich/phpThumb/commit/bd4d594d91cdd3f994699463f989c0aef711413c
You will need to set
$PHPTHUMB_CONFIG['config_disable_realpath'] = true;
in phpThumb.config.php (or $phpThumb->config_disable_realpath = true in object mode)
