### ISSUE TITLE
No temp directory set and none found so none used

### ISSUE THREAD

**Issue by hatzopoulos** [JamesHeinrich/phpThumb#35]
At least on CentOS where the `TMPDIR` is not set by default. If `config_temp_directory` is not set, [`InitializeTempDirSetting()`](https://github.com/JamesHeinrich/phpThumb/blob/fcc8ead9076b605a7cfd4ea7f33995676e6581c7/phpthumb.class.php#L4290-L4292) method fails to find either TMP or TMPDIR environment variables because they do not exist. As such it will not use a temp directory and instead use the current working directory. It might be worthwhile to try other methods of getting a temp directory like perhaps the php ini setting for `upload_tmp_dir` or even `sys_get_temp_dir`.

```php
function InitializeTempDirSetting() {
	$this->config_temp_directory = realpath($this->config_temp_directory ? $this->config_temp_directory : (getenv('TMPDIR') ? getenv('TMPDIR') : getenv('TMP')));
	return true;
}
```

**Comment by JamesHeinrich** [comment]
I have added both ini_get('upload_tmp_dir') and an initial call to sys_get_temp_dir (which didn't exist at the time phpThumb was written).
https://github.com/JamesHeinrich/phpThumb/commit/70c706f19dcbbcf5a6f7a91cea95e0fe2156ade0
