### ISSUE TITLE
Where do I place the config file if installed using composer?

### ISSUE THREAD

**Issue by rquadling** [JamesHeinrich/phpThumb#36]
Hi.

Seems like a silly question, but if installed via composer, there doesn't seem to be any way to supply the config without writing to vendor.

So where do I place the config?

Regards,

Richard.

**Comment by JamesHeinrich** [comment]
I am unfamiliar with Composer, so I'll leave that for someone who is to hopefully answer. If you find the answer yourself please add a comment.

**Comment by rquadling** [comment]
Eh!? You created the composer.json file and made the package available on packagist. Sort of suggest SOME familiarity with composer.

**Comment by JamesHeinrich** [comment]
Nope. I just added what was suggested to me
https://github.com/JamesHeinrich/phpThumb/issues/4

**Comment by rquadling** [comment]
OK. Was it a pull request? If so, maybe the author of that could help.

**Comment by rquadling** [comment]
Ha. So I suppose the right question is where do I put my config file and NOT have it tucked away inside the package?
