### ISSUE TITLE
FR: support for SVG Files

### ISSUE THREAD

**Issue by achterbahn** [JamesHeinrich/phpThumb#37]
It would be great to have phpThumb support the SVG-Format as input format. Output format could be jpg or png.

**Comment by JamesHeinrich** [comment]
I haven't checked, but ImageMagick should be able to handle SVG as an input format. Assuming you have ImageMagick installed and configured into phpThumb then you should already be able to use SVG (and any other format that ImageMagick supports) as an input source to phpThumb.
