### ISSUE TITLE
Can't use ?q= with PNGs

### ISSUE THREAD

**Issue by MartijnOud** [JamesHeinrich/phpThumb#38]
I would like to lower the quality of my thumbnails but because all my images are PNGs this doesn't seem to work.

Demo not working:
`https://www.inktweb.nl/libaries/phpThumb/phpThumb.php?src=/uploads/products/10045/12074_zoom.png&q=10&f=png`

Demo working:
`https://www.inktweb.nl/libaries/phpThumb/phpThumb.php?src=/uploads/products/10045/12074_zoom.png&q=10&f=png`

Looking at `phpthumb.class.php` it seems only `jpeg` uses the `$q` variable but there is support in PHP for PNG quality with `imagepng`.

**Comment by JamesHeinrich** [comment]
Image quality support was added almost exactly a year ago, see https://github.com/JamesHeinrich/phpThumb/issues/24 and https://github.com/JamesHeinrich/phpThumb/commit/813c93ae6486d5b8cd39e1d86b3d504f052f7040

Note that for PNG the &q= argument should be in the range of 0-9, as per the [PHP ImagePNG definition](http://php.net/manual/en/function.imagepng.php) where 0 is no compression and 9 is maximum compression.

Also note that PNG compression levels are not the same as JPEG quality -- PNG is always lossess but higher compression levels may result in a smaller output file at the expense of slower compression.
