### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by peterhough** [JamesHeinrich/phpThumb#4]
Hello,

It would be nice to be able to load the phpThumb library as a dependency using the PHP dependency manager Composer (http://getcomposer.org).

As the project is not currently a Composer package I have to define the repository in my project:

``` json
{
    "name": "My Project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "JamesHeinrich/phpThumb",
                "version": "dev-master",
                "source": {
                    "type": "git",
                    "url": "git://github.com/JamesHeinrich/phpThumb.git",
                    "reference": "master"
                }
            }
        }
    ],
    "require": {
        "JamesHeinrich/phpThumb": "dev-master"
    },
    "autoload": {
        "files": [
            "vendor/JamesHeinrich/phpThumb/phpthumb.class.php"
        ]
    }
}
```

Could the phpThumb library be altered to include a composer.json file that defines it  as a Composer package? 

It would also be lovely if other releases (1.7.11, 1.7.12, etc) are tagged and defined as versions. Then a project can specify which version of the library it requires.

The autoloading of the class might be able to be tidied up too, possibly using the PSR-0 standard.

All the best,
Pete

**Comment by rquadling** [comment]
Hi.

If using composer to install phpThumb, where/how/what is done for the config file? We don't put vendor into our repo and our build images do a composer install prior to activation, so just wondering what the best approach for this is.

Regards,

Richard Quadling.
