### ISSUE TITLE
Fail when memory_limit = -1

### ISSUE THREAD

**Issue by billionaire** [JamesHeinrich/phpThumb#41]
Hi.
I faced with strange behavior when ini_set('memory_limit', -1);.
In theory, when value of -1, no restrictions are imposed on the script, but phpThumb refuses to process images.
I do not know what is the reason, but fix of the glitch might save someone time.
Thank you for your hard work.
Sincerely.

**Comment by JamesHeinrich** [comment]
Let me know if this change doesn't fix it for you
https://github.com/JamesHeinrich/phpThumb/commit/e33e9b9bc4a91cbea6244f5f65866caf52a235ee
