### ISSUE TITLE
Can't get this to work at all

### ISSUE THREAD

**Issue by jcamachott** [JamesHeinrich/phpThumb#42]
I'm lost as to why phpthumb (1.7.14) is not working on my server which was upgraded to 5.3.29 (from 5.2.x).

I have configured both $PHPTHUMB_CONFIG['high_security_password'] and $PHPTHUMB_CONFIG['disable_debug'] = false;

The check page is all green with these exceptions:
- ImageMagick formats displays a white box with "sh: ./identify: No such file or directory"
- php_sapi_name() has an orange box with "cgi-fcgi"

Everything on the demo page is BROKEN except for:

Item 31 - Clubs, foot, hand
Item 50 - white frame, brown frame
Last 2 images under "Demo of phpThumb.demo.showpic.php"

All the "source images, without manipulation" work fine.

I also tried this on two other servers, both running php 5.4. Same problem as above.

Any ideas?

Thanks.

**Comment by jcamachott** [comment]
So again..confused. I got it to work, but I had to:

$PHPTHUMB_CONFIG['disable_debug'] = true

which is NOT recommended in the comments in the config file....???!!

**Comment by JamesHeinrich** [comment]
You're right, the description of ['disable_debug'] in the sample config file is not right. It should read better now: https://github.com/JamesHeinrich/phpThumb/commit/b999c741393133b748b5ea3d8bf06ed9234288d0

**Comment by jcamachott** [comment]
Thank you James
