### ISSUE TITLE
Demo check page to include high_security_password

### ISSUE THREAD

**Issue by jcamachott** [JamesHeinrich/phpThumb#43]
Hi, as high_security_password is supposed to be set in the config, there should be a line in the demo check file that checks for this.

**Comment by JamesHeinrich** [comment]
Added in https://github.com/JamesHeinrich/phpThumb/commit/f32c1217c17c8331e04dc2c74e67060acc91a68d

Note that I'm on the road right now and the above changes are untested, so if you find any issues please reopen this and let me know.
