### ISSUE TITLE
Adding composer support

### ISSUE THREAD

**Issue by xfactor5** [JamesHeinrich/phpThumb#44]
Hi,
Almost all PHP libraries now have composer support. It can be done very easily!
Thanks

**Comment by JamesHeinrich** [comment]
By all means feel free to submit a patch adding whatever additional support you think is required. I don't use Composer myself so I am totally unfamiliar with its requirements. There is already [composer.json](https://github.com/JamesHeinrich/phpThumb/blob/master/composer.json).

**Comment by xfactor5** [comment]
Dude, this is not acceptable. You own this library, the only one qualified to add proper composer support is the main developer. These days you cant avoid composer. It's not something big to learn, getting started for my own project took about just half an hour.
It's really strange that a talented programmer like you, with such a widely used library, says "I am unfamiliar with composer" and I don't wanna try anything new.
