### ISSUE TITLE
Problems with files special caracters

### ISSUE THREAD

**Issue by amineD200** [JamesHeinrich/phpThumb#48]
We use phpThumb in our web site and we are facing problems with files special caracters.
Is there a solution to fix it ?

**Comment by JamesHeinrich** [comment]
That would depend on where you're running into problems. Remember that any parameters passed to phpThumb.php should be URL-encoded, see (rawurlencode)[http://php.net/manual/en/function.rawurlencode.php]

**Comment by amineD200** [comment]
I try this function <a href="http://php.net/manual/en/function.rawurlencode.php">rawurlencode</a> to encode the URL passed to phpThumb.php, nothing was changing

**Comment by JamesHeinrich** [comment]
You'll need to explain your problem better.

**Comment by amineD200** [comment]
the problem be there when running of the command Imagemagick, he found nothing if the path content special characters
I get this error in debug message :
<code>failed to open ".. /thumbnail/../web/Panier%20l%C3%A9gumes%20pour%20site.jpg" SourceImageToGD() [3900] in file "phpthumb.class.php" on line 4118 </code>
