### ISSUE TITLE
Warning: explode(): empty delimiter

### ISSUE THREAD

**Issue by leecollings** [JamesHeinrich/phpThumb#52]
I seem to be having an issue with the phpThumb.config.php file as when I use 

    require_once('phpThumb/phpThumb.config.php');
    <img src="<?php echo htmlspecialchars(phpThumbURL('src='.$gallerySet->before_img.'&w=120', '/phpThumb/phpThumb.php'));?>" alt="Before photo" width="120" height="90" class="img-responsive">

I get a Warning: explode(): empty delimiter in phpThumb.config.php on line 256, which is this:

	foreach (explode($PHPTHUMB_CONFIG['high_security_url_separator'], $ParameterString) as $key_value_pair) {

Any ideas? The separator is showing as `&`

**Comment by JamesHeinrich** [comment]
For whatever reason, at line 256 **$PHPTHUMB_CONFIG['high_security_url_separator']** is empty. It shouldn't be, you'll have to trace through and figure out why it is.

**Comment by leecollings** [comment]
I would appreciate a bit more help if possible. I don't know why it's not reading your config file properly. the phpthumb folder is at the root of my site, but I've noticed that I get the above error message when i use `require_once('phpThumb/phpThumb.config.php')` whereas if I put it to `require_once('/phpThumb/phpThumb.config.php')` then I get No File or directory message. Which I don't understand.

I see lots of people suggesting to use str_split instead of explode. Could it be that the plugin is old and needs re-writing?

**Comment by leecollings** [comment]
Maybe this might help a bit. When debugging, and stepping through the page, you can see the value for the separator is being read as `&`

![image](https://cloud.githubusercontent.com/assets/6681733/12920404/5e0d4440-cf40-11e5-82d5-7cbe09ea3d4e.png)

**Comment by JamesHeinrich** [comment]
PHP function [str_split](http://www.php.net/manual/en/function.str-split.php) is for splitting a string into fixed-length segments, whereas [explode](http://www.php.net/manual/en/function.explode.php) (also [preg_split](http://www.php.net/manual/en/function.preg_split.php), [strtok](http://www.php.net/manual/en/function.strtok.php), etc) split into arbitrary-length segments based on a separator.

Specifying `require_once('/phpThumb/phpThumb.config.php')` would be an absolute filename on an *nix filesystem which is very likely not where your phpThumb files are kept (more likely in something like `/var/www/domain/httpdocs/phpThumb/phpThumb.config.php` or similar).
Either specify the relative filename as you did
`require_once('phpThumb/phpThumb.config.php')`
or explicitly relative to the current directory
`require_once('./phpThumb/phpThumb.config.php')`
or if you prefer you can generate the full absolute filename using something like
`require_once($_SEVER['DOCUMENT_ROOT'].'/phpThumb/phpThumb.config.php')`
or
`require_once(dirname(__FILE__).'/phpThumb/phpThumb.config.php')`


For debugging, I would suggest immediately before the foreach on line 256 insert a `var_dump($PHPTHUMB_CONFIG['high_security_url_separator']` to confirm it is still set by the time the code gets there. You should get `string(1) "&"` output to screen. But if you're getting the empty-separator error then you'll probably get something different.

**Comment by leecollings** [comment]
I'm going to close this, as I noticed that this was using the development version, which I have since replaced with the latest stable.

The code is different, and I'm not experiencing this error anymore, however I am still in need of assistance, but if I need to I'll raise a new issue. Thanks for your help.

**Comment by JamesHeinrich** [comment]
I have just discovered that sometime, I'm not sure exactly when, the config file definition was incorrectly entered as `$PHPTHUMB_CONFIG['config_high_security_url_separator']` instead of `$PHPTHUMB_CONFIG['high_security_url_separator']` -- the shorter version is the correct version, no "config_". Please check your config file and make sure the key is named correctly.
