### ISSUE TITLE
Certain images not showing.

### ISSUE THREAD

**Issue by leecollings** [JamesHeinrich/phpThumb#57]
In the debug file, there seems to be this line that's indicating a problem with the source, but viewing the URL shows the image fine.

`Error opening "https://www.bellavou.co.uk:443/wp-content/uploads/rear-view-woman-weight-loss-tummy-tuck-liposuction-150x150.jpg":`

I have other images on the page displaying okay, and both of tem run on my local copy. Is there anywhere else in the debug file I can look? I have tried clearing cache.

**Comment by leecollings** [comment]
Sorry, always the way. After I posted this, I refreshed the page and the images are loading. Must have been a caching issue.

**Comment by leecollings** [comment]
I want to re-open this, as I've noticed one image of a newly published blog article had the error placeholder. So I deleted all in the cache folder, now all the images show the error image. I refreshed the cache in Cloudflare but no change.

I'd like to know why this is happening, and what can I do to stop it happening? As I Don't want to keep dealing with emptying cache everytime I add a blog article to the site.

Site is www.bellavou.co.uk - you can see examples in 'Before and After' in the sidebar, and 'Blog' at the footer. (the small thumbnail)

**Comment by JamesHeinrich** [comment]
I don't see anything in the sidebar, but I do see error images in the Blog section at the bottom. Of course since I can't view the error details I can't comment further.

One speculation I have is that phpThumb is having trouble retrieving the source image over https.
`phpThumb.php?src=https://www.bellavou.co.uk/wp-content/uploads/`
If possible it is preferred to call phpThumb with local source:
`phpThumb.php?src=/wp-content/uploads/`
I'm not sure if `wp-contents` is mapped to a different directory structure, in which case you may need to fiddle with `$PHPTHUMB_CONFIG['document_root']`.
Failing all that, try changing the src parameter from https to http and see if that fixes the problem (all the resources on your page will still be served over https, it's just the internal call within the server itself to fetch the source image that is http).

**Comment by leecollings** [comment]
None of those changes to the URL seem to change the image when viewed in a new tab. I'll enable debug mode and try and paste the file here.

**Comment by leecollings** [comment]
`phpThumb() v1.7.13-201406261000
http://phpthumb.sourceforge.net

phpThumb() version          = 1.7.13-201406261000
phpversion()                = 5.4.45
PHP_OS                      = Linux
$_SERVER[SERVER_SOFTWARE]   = Apache/2.4.18 (Unix)
__FILE__                    = /home/sites/bellavou.co.uk/public_html/phpThumb/phpthumb.class.php
realpath(.)                 = /home/sites/bellavou.co.uk/public_html/phpThumb
$_SERVER[PHP_SELF]          = /phpThumb/phpThumb.php
$_SERVER[HOST_NAME]         = 
$_SERVER[HTTP_REFERER]      = https://www.bellavou.co.uk/events/facelifts-looking-10-years-younger/
$_SERVER[QUERY_STRING]      = src=https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg&w=60&hash=5f6a36aa66030c7d4aea952c88413a33
$_SERVER[PATH_INFO]         = 
$_SERVER[DOCUMENT_ROOT]     = /home/sites/bellavou.co.uk/public_html/
getenv(DOCUMENT_ROOT)       = /home/sites/bellavou.co.uk/public_html/

get_magic_quotes_gpc()         = FALSE
get_magic_quotes_runtime()     = FALSE
error_reporting()              = integer     32767
ini_get(error_reporting)       = string(1)   "0"
ini_get(display_errors)        = string(1)   "1"
ini_get(allow_url_fopen)       = string(1)   "1"
ini_get(disable_functions)     = string(0)   ""
get_cfg_var(disable_functions) = string(0)   ""
ini_get(safe_mode)             = FALSE
ini_get(open_basedir)          = string(0)   ""
ini_get(max_execution_time)    = string(2)   "60"
ini_get(memory_limit)          = string(4)   "128M"
get_cfg_var(memory_limit)      = string(4)   "128M"
memory_get_usage()             = integer     1928712

$this->config_prefer_imagemagick            = TRUE
$this->config_imagemagick_path              = NULL
$this->ImageMagickWhichConvert()            = /usr/bin/convert
[actual ImageMagick path used]              = string(16)  "/usr/bin/convert"
file_exists([actual ImageMagick path used]) = TRUE
ImageMagickVersion(false)                   = 6.8.3-6 2013-03-15 Q16 
ImageMagickVersion(true)                    = Version: ImageMagick 6.8.3-6 2013-03-15 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2013 ImageMagick Studio LLC
Features: DPC OpenMP Modules
Delegates: bzlib fontconfig freetype gslib jng jp2 jpeg lcms pango png ps rsvg tiff wmf x xml zlib

$this->config_cache_directory               = string(54)  "/home/sites/bellavou.co.uk/public_html/phpThumb/cache/"
$this->config_cache_directory_depth         = integer     2
$this->config_cache_disable_warning         = FALSE
$this->config_cache_maxage                  = integer     18144000
$this->config_cache_maxsize                 = integer     10485760
$this->config_cache_maxfiles                = integer     200
$this->config_cache_force_passthru          = TRUE
$this->cache_filename                       = string(172) "/home/sites/bellavou.co.uk/public_html/phpThumb/cache//9/93/phpThumb_cache_bellavou.co.uk__src9372fa81c13e3b03b234341791d8e416_par82179c205cf1269d56360b59e27fb58d_dat0.jpeg"
is_readable($this->config_cache_directory)  = TRUE
is_writable($this->config_cache_directory)  = TRUE
is_readable($this->cache_filename)          = TRUE
is_writable($this->cache_filename)          = TRUE

$this->config_document_root                  = string(38)  "/home/sites/bellavou.co.uk/public_html"
$this->config_temp_directory                 = string(53)  "/home/sites/bellavou.co.uk/public_html/phpThumb/cache"
$this->config_output_format                  = string(4)   "jpeg"
$this->config_output_maxwidth                = integer     0
$this->config_output_maxheight               = integer     0
$this->config_error_message_image_default    = string(0)   ""
$this->config_error_bgcolor                  = string(6)   "CCCCFF"
$this->config_error_textcolor                = string(6)   "FF0000"
$this->config_error_fontsize                 = integer     1
$this->config_error_die_on_error             = TRUE
$this->config_error_silent_die_on_error      = FALSE
$this->config_error_die_on_source_failure    = TRUE
$this->config_nohotlink_enabled              = TRUE
$this->config_nohotlink_valid_domains        = array(1) {   [0]=>   string(18) "www.bellavou.co.uk" } 
$this->config_nohotlink_erase_image          = TRUE
$this->config_nohotlink_text_message         = string(38)  "Off-server thumbnailing is not allowed"
$this->config_nooffsitelink_enabled          = TRUE
$this->config_nooffsitelink_valid_domains    = array(1) {   [0]=>   string(18) "www.bellavou.co.uk" } 
$this->config_nooffsitelink_require_refer    = FALSE
$this->config_nooffsitelink_erase_image      = FALSE
$this->config_nooffsitelink_text_message     = string(35)  "Image taken from www.bellavou.co.uk"
$this->config_high_security_enabled          = TRUE
$this->config_allow_src_above_docroot        = FALSE
$this->config_allow_src_above_phpthumb       = TRUE
$this->config_max_source_pixels              = float       22369621
$this->config_use_exif_thumbnail_for_speed   = FALSE
$this->config_border_hexcolor                = string(6)   "000000"
$this->config_background_hexcolor            = string(6)   "FFFFFF"
$this->config_ttf_directory                  = string(53)  "/home/sites/bellavou.co.uk/public_html/phpThumb/fonts"
$this->config_disable_pathinfo_parsing       = TRUE
$this->config_disable_imagecopyresampled     = FALSE

$this->phpThumbDebug               = integer     9
$this->thumbnailQuality            = integer     75
$this->thumbnailFormat             = string(4)   "jpeg"
$this->gdimg_output                = resource
$this->gdimg_source                = unknown type
$this->sourceFilename              = string(99)  "https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg"
$this->source_width                = integer     150
$this->source_height               = integer     150
$this->thumbnailCropX              = integer     0
$this->thumbnailCropY              = integer     0
$this->thumbnailCropW              = integer     150
$this->thumbnailCropH              = integer     150
$this->exif_thumbnail_width        = string(0)   ""
$this->exif_thumbnail_height       = string(0)   ""
$this->exif_thumbnail_type         = string(0)   ""
$this->thumbnail_width             = float       60
$this->thumbnail_height            = float       60
$this->thumbnail_image_width       = string(2)   "60"
$this->thumbnail_image_height      = integer     60
strlen($this->rawImageData)        = 0
strlen($this->exif_thumbnail_data) = 0

$this->src  = string(103) "https://www.bellavou.co.uk:443/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg"
$this->new  = NULL
$this->w    = string(2)   "60"
$this->h    = FALSE
$this->f    = string(0)   ""
$this->q    = integer     75
$this->sx   = NULL
$this->sy   = NULL
$this->sw   = NULL
$this->sh   = NULL
$this->far  = NULL
$this->bg   = NULL
$this->bc   = NULL
$this->file = NULL
$this->goto = NULL
$this->err  = NULL
$this->xto  = NULL
$this->ra   = NULL
$this->ar   = NULL
$this->aoe  = NULL
$this->iar  = NULL
$this->maxb = NULL

builtin_function_exists(exif_thumbnail)          = TRUE
builtin_function_exists(gd_info)                 = TRUE
builtin_function_exists(image_type_to_mime_type) = TRUE
builtin_function_exists(GetImageSize)            = TRUE
builtin_function_exists(ImageCopyResampled)      = TRUE
builtin_function_exists(ImageCopyResized)        = TRUE
builtin_function_exists(ImageCreate)             = TRUE
builtin_function_exists(ImageCreateFromString)   = TRUE
builtin_function_exists(ImageCreateTrueColor)    = TRUE
builtin_function_exists(ImageIsTrueColor)        = TRUE
builtin_function_exists(ImageRotate)             = TRUE
builtin_function_exists(ImageTypes)              = TRUE
builtin_function_exists(version_compare)         = TRUE
builtin_function_exists(ImageCreateFromGIF)      = TRUE
builtin_function_exists(ImageCreateFromJPEG)     = TRUE
builtin_function_exists(ImageCreateFromPNG)      = TRUE
builtin_function_exists(ImageCreateFromWBMP)     = TRUE
builtin_function_exists(ImageCreateFromXBM)      = TRUE
builtin_function_exists(ImageCreateFromXPM)      = TRUE
builtin_function_exists(ImageCreateFromString)   = TRUE
builtin_function_exists(ImageCreateFromGD)       = TRUE
builtin_function_exists(ImageCreateFromGD2)      = TRUE
builtin_function_exists(ImageCreateFromGD2Part)  = TRUE
builtin_function_exists(ImageJPEG)               = TRUE
builtin_function_exists(ImageGIF)                = TRUE
builtin_function_exists(ImagePNG)                = TRUE
builtin_function_exists(ImageWBMP)               = TRUE

gd_info.GD Version                         = string(26)  "bundled (2.1.0 compatible)"
gd_info.FreeType Support                   = TRUE
gd_info.FreeType Linkage                   = string(13)  "with freetype"
gd_info.T1Lib Support                      = TRUE
gd_info.GIF Read Support                   = TRUE
gd_info.GIF Create Support                 = TRUE
gd_info.JPEG Support                       = TRUE
gd_info.PNG Support                        = TRUE
gd_info.WBMP Support                       = TRUE
gd_info.XPM Support                        = TRUE
gd_info.XBM Support                        = TRUE
gd_info.JIS-mapped Japanese Font Support   = FALSE

exif_info.EXIF Support               = string(7)   "enabled"
exif_info.EXIF Version               = string(51)  "1.4 $Id: 05041c5f0094cb46d9b516bd624d593b90cc38f9 $"
exif_info.Supported EXIF Version     = string(4)   "0220"
exif_info.Supported filetypes        = string(9)   "JPEG,TIFF"

ApacheLookupURIarray() -- FAILED

$_GET[src]                           = string(99)  "https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg"
$_GET[w]                             = string(2)   "60"
$_GET[hash]                          = string(32)  "5f6a36aa66030c7d4aea952c88413a33"
$_GET[phpThumbDebug]                 = integer     9

$this->debugmessages:
  * phpThumb() v1.7.13-201406261000 in file "phpthumb.class.php" on line 220
  * setParameter(config_document_root, string(38)  "/home/sites/bellavou.co.uk/public_html") in file "phpThumb.php" on line 152
  * setParameter(config_high_security_enabled, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_high_security_url_separator, string(1)   "&") in file "phpThumb.php" on line 152
  * setParameter(config_disable_debug, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_allow_src_above_docroot, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_allow_src_above_phpthumb, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_auto_allow_symlinks, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_additional_allowed_dirs, array(0) { } ) in file "phpThumb.php" on line 152
  * setParameter(config_cache_directory, string(54)  "/home/sites/bellavou.co.uk/public_html/phpThumb/cache/") in file "phpThumb.php" on line 152
  * setParameter(config_cache_disable_warning, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_cache_directory_depth, integer     2) in file "phpThumb.php" on line 152
  * setParameter(config_cache_maxage, integer     18144000) in file "phpThumb.php" on line 152
  * setParameter(config_cache_maxsize, integer     10485760) in file "phpThumb.php" on line 152
  * setParameter(config_cache_maxfiles, integer     200) in file "phpThumb.php" on line 152
  * setParameter(config_cache_source_enabled, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_cache_source_directory, string(61)  "/home/sites/bellavou.co.uk/public_html/phpThumb/cache/source/") in file "phpThumb.php" on line 152
  * setParameter(config_cache_source_filemtime_ignore_local, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_cache_source_filemtime_ignore_remote, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_cache_default_only_suffix, string(0)   "") in file "phpThumb.php" on line 152
  * setParameter(config_cache_prefix, string(30)  "phpThumb_cache_bellavou.co.uk_") in file "phpThumb.php" on line 152
  * setParameter(config_cache_force_passthru, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_temp_directory, string(54)  "/home/sites/bellavou.co.uk/public_html/phpThumb/cache/") in file "phpThumb.php" on line 152
  * setParameter(config_prefer_imagemagick, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_imagemagick_use_thumbnail, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_imagemagick_path, NULL) in file "phpThumb.php" on line 152
  * setParameter(config_max_source_pixels, float       22369621) in file "phpThumb.php" on line 152
  * setParameter(config_output_format, string(4)   "jpeg") in file "phpThumb.php" on line 152
  * setParameter(config_output_maxwidth, integer     0) in file "phpThumb.php" on line 152
  * setParameter(config_output_maxheight, integer     0) in file "phpThumb.php" on line 152
  * setParameter(config_output_interlace, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_error_image_width, integer     400) in file "phpThumb.php" on line 152
  * setParameter(config_error_image_height, integer     100) in file "phpThumb.php" on line 152
  * setParameter(config_error_message_image_default, string(0)   "") in file "phpThumb.php" on line 152
  * setParameter(config_error_bgcolor, string(6)   "CCCCFF") in file "phpThumb.php" on line 152
  * setParameter(config_error_textcolor, string(6)   "FF0000") in file "phpThumb.php" on line 152
  * setParameter(config_error_fontsize, integer     1) in file "phpThumb.php" on line 152
  * setParameter(config_error_die_on_error, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_error_silent_die_on_error, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_error_die_on_source_failure, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_nohotlink_enabled, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_nohotlink_valid_domains, array(1) {   [0]=>   string(18) "www.bellavou.co.uk" } ) in file "phpThumb.php" on line 152
  * setParameter(config_nohotlink_erase_image, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_nohotlink_text_message, string(38)  "Off-server thumbnailing is not allowed") in file "phpThumb.php" on line 152
  * setParameter(config_nooffsitelink_enabled, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_nooffsitelink_valid_domains, array(1) {   [0]=>   string(18) "www.bellavou.co.uk" } ) in file "phpThumb.php" on line 152
  * setParameter(config_nooffsitelink_require_refer, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_nooffsitelink_erase_image, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_nooffsitelink_watermark_src, string(26)  "/demo/images/watermark.png") in file "phpThumb.php" on line 152
  * setParameter(config_nooffsitelink_text_message, string(35)  "Image taken from www.bellavou.co.uk") in file "phpThumb.php" on line 152
  * setParameter(config_border_hexcolor, string(6)   "000000") in file "phpThumb.php" on line 152
  * setParameter(config_background_hexcolor, string(6)   "FFFFFF") in file "phpThumb.php" on line 152
  * setParameter(config_ttf_directory, string(53)  "/home/sites/bellavou.co.uk/public_html/phpThumb/fonts") in file "phpThumb.php" on line 152
  * setParameter(config_http_user_agent, string(109) "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36") in file "phpThumb.php" on line 152
  * setParameter(config_disable_pathinfo_parsing, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_disable_imagecopyresampled, FALSE) in file "phpThumb.php" on line 152
  * setParameter(config_disable_onlycreateable_passthru, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_http_fopen_timeout, integer     10) in file "phpThumb.php" on line 152
  * setParameter(config_http_follow_redirect, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_allow_local_http_src, TRUE) in file "phpThumb.php" on line 152
  * setParameter(config_use_exif_thumbnail_for_speed, FALSE) in file "phpThumb.php" on line 152
  * setParameter(src, string(99)  "https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg") in file "phpThumb.php" on line 329
  * setSourceFilename(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) set $this->sourceFilename to "https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg" in file "phpthumb.class.php" on line 271
  * setParameter(w, string(2)   "60") in file "phpThumb.php" on line 329
  * setParameter(hash, string(32)  "5f6a36aa66030c7d4aea952c88413a33") in file "phpThumb.php" on line 329
  * setParameter(phpThumbDebug, integer     9) in file "phpThumb.php" on line 329
  * $CanPassThroughDirectly=false because !@is_readable(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) in file "phpThumb.php" on line 376
  * $CanPassThroughDirectly=false because $_GET[hash] are set in file "phpThumb.php" on line 410
  * $CanPassThroughDirectly="0" && $phpThumb->src="https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg" in file "phpThumb.php" on line 421
  * Addding ImageMagick formats to $AvailableImageOutputFormats (text;ico;bmp;wbmp;gif;png;jpeg) in file "phpthumb.class.php" on line 919
  * $AvailableImageOutputFormats = array(text;ico;bmp;wbmp;gif;png;jpeg) in file "phpthumb.class.php" on line 925
  * $this->thumbnailFormat set to $this->config_output_format "jpeg" in file "phpthumb.class.php" on line 936
  * $this->thumbnailQuality set to "75" in file "phpthumb.class.php" on line 953
  * SetCacheFilename() _src set from md5($this->sourceFilename) "https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg" = "9372fa81c13e3b03b234341791d8e416" in file "phpthumb.class.php" on line 3443
  * SetCacheFilename() _par set from md5(_w60_dpi150_q75) in file "phpthumb.class.php" on line 3476
  * Cached file "/home/sites/bellavou.co.uk/public_html/phpThumb/cache//9/93/phpThumb_cache_bellavou.co.uk__src9372fa81c13e3b03b234341791d8e416_par82179c205cf1269d56360b59e27fb58d_dat0.jpeg" does not exist, processing as normal in file "phpThumb.php" on line 511
  * $phpThumb->src (https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) is remote image, attempting to download in file "phpThumb.php" on line 557
  * Setting "user_agent" to "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36" in file "phpThumb.php" on line 559
  * CleanUpURLencoding(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) returned "https://www.bellavou.co.uk:443/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg" in file "phpThumb.php" on line 563
  * phpThumb() v1.7.13-201406261000
http://phpthumb.sourceforge.net

Error opening "https://www.bellavou.co.uk:443/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg":

400 Bad Request in file "phpthumb.class.php" on line 4050
  * $this->sourceFilename set to "https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg" in file "phpthumb.class.php" on line 849
  * $this->cache_filename already set, skipping SetCacheFilename() in file "phpthumb.class.php" on line 3398
  * starting ExtractEXIFgetImageSize() in file "phpthumb.class.php" on line 3236
  * GetImageSize(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) says image is 150x150 in file "phpthumb.class.php" on line 3246
  * $this->useRawIMoutput=true after checking $UnAllowedParameters in file "phpthumb.class.php" on line 1508
  * phpThumb_tempnam() returning "/home/sites/bellavou.co.uk/public_html/phpThumb/cache/pThumb3ptD74" in file "phpthumb.class.php" on line 4275
  * ImageMagickSwitchAvailable(thumbnail) = 1 in file "phpthumb.class.php" on line 1445
  * ImageMagickSwitchAvailable(density) = 1 in file "phpthumb.class.php" on line 1445
  * GetImageSize(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) SUCCEEDED: Array
(
    [0] => 150
    [1] => 150
    [2] => 2
    [3] => width="150" height="150"
    [bits] => 8
    [channels] => 3
    [mime] => image/jpeg
)
 in file "phpthumb.class.php" on line 1600
  * GetImageSize(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) returned [w=150;h=150;f=2] in file "phpthumb.class.php" on line 1605
  * source dimensions set to 150x150 in file "phpthumb.class.php" on line 1608
  * SetOrientationDependantWidthHeight() starting with "150"x"150" in file "phpthumb.class.php" on line 3215
  * SetOrientationDependantWidthHeight() setting w="60", h="0" in file "phpthumb.class.php" on line 3231
  * Remaining $this->fltr after ImageMagick: (array(0) { } ) in file "phpthumb.class.php" on line 2132
  * ImageMagickSwitchAvailable(quality;interlace) = 1 in file "phpthumb.class.php" on line 1442
  * ImageMagick called as (convert -density '150' -background '#FFFFFF' -thumbnail '60x' -quality '75' -interlace line  'https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg[0]' jpeg:'/home/sites/bellavou.co.uk/public_html/phpThumb/cache/pThumb3ptD74' 2>&1) in file "phpthumb.class.php" on line 2151
  * ImageMagick failed with message (convert.x: delegate failed `"curl" -s -k -o "%o" "https:%M"' @ error/delegate.c/InvokeDelegate/1065.
convert.x: unable to open image `/dev/shm/magick-45828ycsuEnJTSfC1': No such file or directory @ error/blob.c/OpenBlob/2641.
convert.x: unable to open file `/dev/shm/magick-45828ycsuEnJTSfC1': No such file or directory @ error/constitute.c/ReadImage/589.
convert.x: no images defined `jpeg:/home/sites/bellavou.co.uk/public_html/phpThumb/cache/pThumb3ptD74' @ error/convert.c/ConvertImageCommand/3068.) in file "phpthumb.class.php" on line 2156
  * deleting "/home/sites/bellavou.co.uk/public_html/phpThumb/cache/pThumb3ptD74" in file "phpthumb.class.php" on line 2188
  * ImageMagickThumbnailToGD() failed in file "phpthumb.class.php" on line 3286
  * SetOrientationDependantWidthHeight() starting with "150"x"150" in file "phpthumb.class.php" on line 3215
  * SetOrientationDependantWidthHeight() setting w="60", h="0" in file "phpthumb.class.php" on line 3231
  * EXIF thumbnail extraction: (size=0; type=""; 0x0) in file "phpthumb.class.php" on line 3343
  * starting SourceImageToGD() in file "phpthumb.class.php" on line 3603
  * starting ImageCreateFromFilename(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) in file "phpthumb.class.php" on line 3518
  * ImageCreateFromFilename found ($getimagesizeinfo[2]==2) in file "phpthumb.class.php" on line 3527
  * Calling ImageCreateFromJPEG(https://www.bellavou.co.uk/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg) in file "phpthumb.class.php" on line 3535
  * Not using EXIF thumbnail data because $this->gdimg_source is already set in file "phpthumb.class.php" on line 3670
  * CalculateThumbnailDimensions() starting with [W,H,sx,sy,sw,sh] initially set to [150,150,,,,] in file "phpthumb.class.php" on line 3086
  * CalculateThumbnailDimensions() starting with [x,y,w,h] initially set to [0,0,150,150] in file "phpthumb.class.php" on line 3101
  * CreateGDoutput() returning canvas "60x60" in file "phpthumb.class.php" on line 3210
  * ImageResizeFunction($o, $s, 0, 0, 0, 0, 60, 60, 150, 150) in file "phpthumb.class.php" on line 4253
  * memory_get_usage() after copy-resize = 2016160 in file "phpthumb.class.php" on line 403
  * memory_get_usage() after ImageDestroy = 1888880 in file "phpthumb.class.php" on line 405
  * AntiOffsiteLinking() checking $_SERVER[HTTP_REFERER] "https://www.bellavou.co.uk/events/facelifts-looking-10-years-younger/" in file "phpthumb.class.php" on line 2366
  * AntiOffsiteLinking() - "www.bellavou.co.uk" is in $this->config_nooffsitelink_valid_domains (www.bellavou.co.uk) in file "phpthumb.class.php" on line 2380
  * AntiOffsiteLinking() - "www.bellavou.co.uk" is in $this->config_nohotlink_valid_domains (www.bellavou.co.uk) in file "phpthumb.class.php" on line 2394
  * AntiOffsiteLinking() says this is allowed in file "phpthumb.class.php" on line 2399
  * skipping AlphaChannelFlatten() because !$this->is_alpha in file "phpthumb.class.php" on line 2455
  * GenerateThumbnail() completed successfully in file "phpthumb.class.php" on line 417
  * CleanUpCacheDirectory() set to purge (210.0 days; 10.00 MB; 200 files) in file "phpthumb.class.php" on line 667
  * CleanUpCacheDirectory() skipped because "/home/sites/bellavou.co.uk/public_html/phpThumb/cache//phpThumbCacheStats.txt" is recently modified in file "phpthumb.class.php" on line 677
  * RenderOutput() attempting ImageJPEG($this->gdimg_output) in file "phpthumb.class.php" on line 446
  * RenderOutput() completing with $this->outputImageData = 1903 bytes in file "phpthumb.class.php" on line 526
  * RenderToFile(/home/sites/bellavou.co.uk/public_html/phpThumb/cache//9/93/phpThumb_cache_bellavou.co.uk__src9372fa81c13e3b03b234341791d8e416_par82179c205cf1269d56360b59e27fb58d_dat0.jpeg) succeeded in file "phpthumb.class.php" on line 554
  * Would have used cached file, but skipping due to phpThumbDebug in file "phpThumb.php" on line 66
  * * Would have sent headers (1): Last-Modified: Fri, 26 Feb 2016 13:16:55 GMT in file "phpThumb.php" on line 67
  * * Would have sent headers (2): Content-Type: image/jpeg in file "phpThumb.php" on line 69
  * * Would have sent headers (3): Location: /phpThumb/cache//9/93/phpThumb_cache_bellavou.co.uk__src9372fa81c13e3b03b234341791d8e416_par82179c205cf1269d56360b59e27fb58d_dat0.jpeg in file "phpThumb.php" on line 72

$this->debugtiming:
  * 1456492615.289509 : phpThumb() constructor in file "phpthumb.class.php" on line 219
  * 1456492615.274312 : phpThumb.php start in file "phpThumb.php" on line 119
  * 1456492615.291985 : phpThumbDebug[0] in file "phpThumb.php" on line 211
  * 1456492615.292009 : phpThumbDebug[1] in file "phpThumb.php" on line 267
  * 1456492615.292065 : phpThumbDebug[2] in file "phpThumb.php" on line 314
  * 1456492615.292149 : phpThumbDebug[3] in file "phpThumb.php" on line 348
  * 1456492615.292191 : phpThumbDebug[4] in file "phpThumb.php" on line 415
  * 1456492615.292216 : phpThumbDebug[5] in file "phpThumb.php" on line 500
  * 1456492615.293247 : phpThumbDebug[6] in file "phpThumb.php" on line 516
  * 1456492615.305778 : phpThumbDebug[7] in file "phpThumb.php" on line 581
  * 1456492615.895723 : phpThumbDebug[8] in file "phpThumb.php" on line 591
  * 1456492615.897777 : skipped using cached image in file "phpThumb.php" on line 65
  * 1456492615.898117 : phpThumbDebug[9] in file "phpThumb.php" on line 624
  * Total processing time: 0.623805`

**Comment by JamesHeinrich** [comment]
This is your core problem, as suspected a problem opening the https-source image:
```
Error opening "https://www.bellavou.co.uk:443/wp-content/uploads/happy-couple-bed-smiling-face-body-dental-150x150.jpg":
400 Bad Request
```
Try again with the local source. Where is `wp-content/uploads` in your filesystem relative to document_root for this site? Figure that out, adjust the src to match, make any allowances in `$PHPTHUMB_CONFIG['additional_allowed_dirs']`, `$PHPTHUMB_CONFIG['allow_src_above_docroot']`, `$PHPTHUMB_CONFIG['allow_src_above_phpthumb']` as needed.

**Comment by leecollings** [comment]
This is what I don't understand. I can easily open that URL in a browser, and it displays the image. 

UPDATE: It seemed that after I disabled debug mode and loaded, the images load up. Maybe this is what I did last time...? Strange because nothing's changed, and the src is still set with the https:// at the start.. but the image is now displaying.

So, it does work. But there must be something happening initially that's stopping. But not fatal enough, as after the debug mode is turned off it seems to work. Are there any cleanup actions that take place when debug mode is disabled? Does this flush the cache?

**Comment by JamesHeinrich** [comment]
I noticed when reviewing your log that CleanUpURLencoding() is adding in the port number, but if I try accessing the image in my browser with the port number it redirects
Please try editing [phpthumb.functions.php line 722](https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.functions.php#L722) to exclude port 443 as well:
```
$cleaned_url .= ((!empty($parse_url['port']) && ($parse_url['port'] != 80) && ($parse_url['port'] != 443)) ? ':'.$parse_url['port'] : '');
```

**Comment by leecollings** [comment]
Thanks for that, I've changed that and will see how it performs from now on.

**Comment by JamesHeinrich** [comment]
Opening an HTTPS URL in your browser is one thing, since browsers are highly developed, continually updated, and will support virtually everything. Opening HTTPS via PHP, cURL, wget, etc is something entirely different since not everything will support HTTPS, either at all or completely, there may be dependencies, etc.

As a general principle, if you can avoid HTTPS calls you'll have an easier time. If you can supply local filenames for phpThumb even better, performance will be much-improved as well.

**Comment by leecollings** [comment]
James, I've updated the phpThumb.php to your latest version, as referenced in a previous issue I Created.

But when reloading the page, none of the images are displaying now. I'm really concerned that it seems any change followed by a refresh causes the images to not display, and the reliability of this plugin.

The site is now running at http://146.148.112.239/ - And currently on my computer, neither the sidebar or images at the footer are loading now.

Are you able to help diagnose this at all?

**Comment by leecollings** [comment]
When viewing an image, I'm getting this: 
`
Fatal error: Call to undefined method phpthumb_functions::PasswordStrength() in /var/www/html/phpThumb/phpThumb.php on line 193`

**Comment by leecollings** [comment]
Turns out there was the function missing in the functions file. I must be using old files.

If I download a whole ZIP of the current files, is it as easy as an upload to overwrite existing files? Or are there only a few select files I need to update?

**Comment by JamesHeinrich** [comment]
Upgrading to the latest version should be a simple matter of downloading the zip file, overwrite all existing files with the latest version. The only file you want to be careful with is your config file, which is why it is distributed as `phpThumb.config.php.default` so it won't overwrite your existing file. However it would be better to migrate your settings to the new config file, depending how old your existing config file is. At the very least you should copy the phpThumbURL() function from the bottom to make sure you're using the current version of that.
