### ISSUE TITLE
 $PHPTHUMB_CONFIG assuming global scope

### ISSUE THREAD

**Issue by loki0609** [JamesHeinrich/phpThumb#60]
I just ran into this trying to implement phpThumb with codeigniter. 

In the controller you include the config file
 `include 'apps/phpThumb/phpThumb.config.php';`

then in your view you are calling the phpThumbUrl
`<?php echo '<img src="'.htmlspecialchars(phpThumbURL('src=/s3fs/workorders/il005/42&w=150', '/apps/phpThumb/phpThumb.php')).'">';?>`

The problem is in phpThumb.config.php on line 254 within the phpThumbURL function
`global $PHPTHUMB_CONFIG;`

You are assuming that $PHPTHUMB_CONFIG is still in the global scope when it's not in this case. You must declare global $PHPTHUMB_CONFIG; so the function can access it. I just declared it in my controller like this:

`global $PHPTHUMB_CONFIG;`
`include 'apps/phpThumb/phpThumb.config.php';`

**Comment by JamesHeinrich** [comment]
Sorry, I'm not sure I follow which file(s) you're talking about.

You say 
> In the controller you include the config file
> `include 'apps/phpThumb/phpThumb.config.php';`

But I'm not sure which "controller" you mean? Which file and line contains this call? Are you sure that's phpThumb code? That `include` statement doesn't look like my code-formatting style.

**Comment by arturmamedov** [comment]
I confirm this issue!

`\phpthumb\phpThumb.config.php` in the function __phpThumbURL__
```
function phpThumbURL($ParameterString, $path_to_phpThumb='phpThumb.php') {
	global $PHPTHUMB_CONFIG;
```
use the `global $PHPTHUMB_CONFIG;` but if you debug this one are empty `NULL`!

For solve, need to add the definition of `global $PHPTHUMB_CONFIG;` at the begin of `phpThumb.config.php`

**Comment by arturmamedov** [comment]
Or how in previous versions ad to globals `$GLOBALS['PHPTHUMB_CONFIG'] = $PHPTHUMB_CONFIG;`

This is in `v1.12`
```
$GLOBALS['PHPTHUMB_CONFIG'] = $PHPTHUMB_CONFIG;
function phpThumbURL($ParameterString, $path_to_phpThumb = 'phpThumb.php')
{
    global $PHPTHUMB_CONFIG;

    return $path_to_phpThumb.'?'.$ParameterString.$PHPTHUMB_CONFIG['high_security_url_separator'].'hash='.md5($ParameterString.$PHPTHUMB_CONFIG['high_security_password']);
}
```

**Comment by JamesHeinrich** [comment]
Hopefully fixed with https://github.com/JamesHeinrich/phpThumb/commit/551aeb75baaabd7ef12b3923d6761a51e4a11959
