### ISSUE TITLE
failed to open "test/phpThumb/images/" error

### ISSUE THREAD

**Issue by HillbillyGeek** [JamesHeinrich/phpThumb#62]
Am using this value the "phpThumb :: sample photo gallery demo" page:

`$basedir = 'test/phpThumb/images/';    `
(this is the path to my webroot for the images folder, as exists in the unzipped directory...)
I am using this on my local web server; All files have good permissions, and the phpThumb.demo.check.php page gives acceptable results except for one red item:
php_sapi_name(): apache2handler

I get;
`This is a demo of how you can use phpThumb() in an image gallery.
failed to open "test/phpThumb/images/" `

I am using this on my local web server; All files have good permissions, and the phpThumb.demo.check.php page gives acceptable results except for one red item:
php_sapi_name(): apache2handler

The sample photo gallery almost works on my production server, which shows in orange: 
php_sapi_name(): cgi-fcgi

The page comes up, but the images are broken; opening the images in another tab
references
`phpThumb.php?src=test%2FphpThumb%2Fimages%2F%2Fmask05.png&zc=1&w=120&h=120`

**Comment by JamesHeinrich** [comment]
You'll need to recheck the pathnames to ensure they exist, and that you're referring to the directory you think you are (checking document_root in the config, specifying absolute pathnames, etc). If you have trouble, enable debug mode, open a phpThumb image in your browser, and peruse the debug code, at some point you'll see it attempting to resolve the src parameter to an absolute filename and you should be able to see where it's going wrong.

**Comment by HillbillyGeek** [comment]
OK: on my local server (laptop) the gallery table displays with:
`$basedir = '../images';
$thumb   = '../phpThumb.php';
$popup   = '../phpThumb.demo.showpic.php';`
on the production server, it needs:
`$basedir = 'test/phpThumb/images/'; 
$thumb   = 'test/phpThumb/phpThumb.php'; 
$popup   = 'test/phpThumb/demo/phpThumb.demo.showpic.php'; `

Both pages display the tables, but the src for the images is:
`<img src="test/phpThumb/phpThumb.php?src=test/phpThumb/images//lilies.jpg&amp;zc=1&amp;w=120&amp;h=120" border="1" width="120" height="120" alt="lilies.jpg">`

it seems to be adding in, or duplicating the all for the image twice...

**Comment by HillbillyGeek** [comment]
Admitedly, I'm probably overlooking something very basic, but I haven't noticed this dichotomy before.

**Comment by JamesHeinrich** [comment]
To be clear, are we just talking about the demo file [phpThumb.demo.gallery.php](https://github.com/JamesHeinrich/phpThumb/blob/master/demo/phpThumb.demo.gallery.php)?

**Comment by HillbillyGeek** [comment]
Yes

**Comment by HillbillyGeek** [comment]
You can see it here
http://hillbillygeek.net/test/phpThumb/demo/phpThumb.demo.gallery.php

**Comment by HillbillyGeek** [comment]
I am using an older version from 2009 that works well, but was looking to upgrade...

**Comment by JamesHeinrich** [comment]
You're referring to "test/images/filename.jpg", which is relative to phpThumb.php
So you're trying to thumbnail, for example
`/test/phpThumb/demo/test/phpThumb/test/phpThumb/images/lilies.jpg`
instead of 
`test/phpThumb/images/lilies.jpg`

Try specifying your path names as relative-to-webroot, like
`/test/phpThumb/images/` instead of
`test/phpThumb/images/`

**Comment by JamesHeinrich** [comment]
Please upgrade to the current release before reporting bugs or issues, thanks.

**Comment by HillbillyGeek** [comment]
I am working on a download of the current version: trying to understand it. sorry if I'm out of line here...

**Comment by JamesHeinrich** [comment]
Current version is always available here:
https://github.com/JamesHeinrich/phpThumb/archive/master.zip
