### ISSUE TITLE
Undefined variable $mask_filename

### ISSUE THREAD

**Issue by Jako** [JamesHeinrich/phpThumb#63]
The variable $mask_filename seems to be not defined in the following line:
https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php#L3085

**Comment by JamesHeinrich** [comment]
Thanks, fixed in https://github.com/JamesHeinrich/phpThumb/commit/a094bda167f047cd49bce25eab211cc3387b1c96
