### ISSUE TITLE
Wrong &&

### ISSUE THREAD

**Issue by mambax7** [JamesHeinrich/phpThumb#69]
I assume that the line 2850 in phpthumb.class.php
```php
if (($margin > 1) && ($margin < 1)) {
```
should be:
```php
if (($margin > 1) || ($margin < 1)) {
```

**Comment by JamesHeinrich** [comment]
Thanks. The `&&` is correct but it should be between 0-1, where the value is interpreted as a percentage rather than an absolute amount.

Fixed in https://github.com/JamesHeinrich/phpThumb/commit/fa6d905ffd16e5a80c88e050b73e1a6f2609e011
