### ISSUE TITLE
Does it make sense for phpThumb, to always set a default timezone if one is not set ?

### ISSUE THREAD

**Issue by ggppdk** [JamesHeinrich/phpThumb#70]
If it does set a default one,
 we will get less support requests / complaints from users ...
```
// Set a default timezone if web server has not done already in php.ini
if ( ini_get('date.timezone')=='' && version_compare(phpversion(), '5.1.0', '>'))
{
	date_default_timezone_set('UTC');
}
```
Or is it better to let it fail ?

> Strict Standards: strtotime(): It is not safe to rely on the system's timezone settings.
> You are *required* to use the date.timezone setting or the date_default_timezone_set() function.
> In case you used any of those methods and you are still getting this warning, you most likely
> misspelled the timezone identifier  ....

**Comment by JamesHeinrich** [comment]
Makes sense. I spent yesterday dealing with just such an issue.

I changed your code slightly and implemented in https://github.com/JamesHeinrich/phpThumb/commit/6d672f2c132a4135e560c2ba86b81758a15fc94e

**Comment by ggppdk** [comment]
Hello

thanks, i have been adding this change  (**default timezone**) to the file **phpThumb.php**or a couple of years now, after several reports by users

Question
- you may want set a default timezone to the main class file too:  phpthumb.class.php

The above is for the usage case that we call phpThumb via instatiating the class, instead of calling it via a URL
- this should be safe too, because any developer doing a similar check, and setting a default timezone, **can do before calling phpThumb** class ?
- but this is less important to add, because we can do it without hacking phpthumb.class.php

**Comment by JamesHeinrich** [comment]
I think it's useful in phpThumb.php which is called standalone, and sometimes by users who don't know much about programming. But I think anyone using phpthumb.class directly should be left to configure their server correctly, so I don't think I want to add it to phpthumb.class.php
