### ISSUE TITLE
Windows Latin 1 charset

### ISSUE THREAD

**Issue by Jako** [JamesHeinrich/phpThumb#73]
The name of Torstein Hønsi looks wrong, if you don't edit the file with the Windows Latin 1 charset. Maybe it is better to encode both files with that name in UTF-8 (/phpthumb.filters.php and phpthumb.unsharp.php) - without a BOM for sure.

**Comment by JamesHeinrich** [comment]
Thanks, fixed in https://github.com/JamesHeinrich/phpThumb/commit/3bd90be695b11933310c6875440336a5b79d524a
