### ISSUE TITLE
Demo page does not work on PHP 7

### ISSUE THREAD

**Issue by camilou** [JamesHeinrich/phpThumb#77]
Using the latest version of the scripts, i am trying to make it work on an Apache 2.4 + PHP 7.0.X setup, the script works fine on older PHP versions, but not this one.

After the debug, i get the whole detail, but an specific description that goes like this:

```
ERROR: invalid hash in file "phpthumb.class.php" on line 4131
  * setParameter(src, string(16)  "images/small.jpg") in file "phpThumb.php" on line 383
  * resolvePath: /var/www/html/phpThumb/images/small.jpg (allowed_dirs: Array
(
    [0] => /var/www/html/phpThumb/images/
)
) in file "phpthumb.class.php" on line 1140
```

Is this a known issue? Any clue about why is it happening?

Thanks in advance!

**Comment by JamesHeinrich** [comment]
I assume you're familiar in general with the [image hash and phpThumbURL()](http://support.silisoftware.com/phpBB3/viewtopic.php?t=952) concepts in phpThumb.

Can you confirm if:
a) there is a &h= parameter being generated for the img src
b) if so does it have a hash value, or is it empty
and we'll go from there.

**Comment by joomla-ua** [comment]
phpthumb.class.php support PHP 7.1!

**Comment by JamesHeinrich** [comment]
No response from original poster for more than a year, closing issue.
