### ISSUE TITLE
SourceImageToGD() failed in file "phpthumb.class.php" on line 374

### ISSUE THREAD

**Issue by ThiloL** [JamesHeinrich/phpThumb#83]
What could be the problem? Has it to with PHP 7.0?
And: ImageMagickThumbnailToGD() failed in file "phpthumb.class.php" on line 3805

**Comment by JamesHeinrich** [comment]
You'll have to enable debug mode and see more specifically in the detailed logs what exactly is failing., probably in the line or two just above that message.

**Comment by ThiloL** [comment]
phpThumb() v1.7.14-201608101311
http://phpthumb.sourceforge.net

Error messages disabled.

edit phpThumb.config.php and (temporarily) set
$PHPTHUMB_CONFIG['disable_debug'] = false;
to view the details of this error

phpThumb() v1.7.14-201608101311 in file "phpthumb.class.php" on line 229

setSourceFilename(/kunden/homepages/24/d147901974/htdocs/_feuerwehr/bildarchiv/2017/[20170422] Busfahrt Bamberg/FFW_Heubisch_Busfahrt_Bamberg_20170422_001.jpg) set $this->sourceFilename to "/kunden/homepages/24/d147901974/htdocs/_feuerwehr/bildarchiv/2017/[20170422] Busfahrt Bamberg/FFW_Heubisch_Busfahrt_Bamberg_20170422_001.jpg" in file "phpthumb.class.php" on line 294

                  file_exists() = 0 in file "phpthumb.class.php" on line 1419

file_exists_ignoreopenbasedir() = 0 in file "phpthumb.class.php" on line 1420

                      is_file() = 0 in file "phpthumb.class.php" on line 1421

                is_executable() = 0 in file "phpthumb.class.php" on line 1422

using ImageMagick path from `which convert` (/usr/bin/convert) in file "phpthumb.class.php" on line 1443

ImageMagick version checked with "convert --version" in file "phpthumb.class.php" on line 1485

ImageMagick convert --version says "Version: ImageMagick 6.8.9-9 Q16 " in file "phpthumb.class.php" on line 1493

Addding ImageMagick formats to $AvailableImageOutputFormats (text;ico;bmp;wbmp;gif;png;jpeg) in file "phpthumb.class.php" on line 963

$AvailableImageOutputFormats = array(text;ico;bmp;wbmp;gif;png;jpeg) in file "phpthumb.class.php" on line 969

$this->thumbnailFormat set to $this->config_output_format "jpeg" in file "phpthumb.class.php" on line 980

$this->thumbnailQuality set to "50" in file "phpthumb.class.php" on line 997

resolvePath: /kunden/homepages/24/d147901974/htdocs/_feuerwehr/bildarchiv/2017/[20170422] Busfahrt Bamberg/FFW_Heubisch_Busfahrt_Bamberg_20170422_001.jpg (allowed_dirs: Array
(
)
) in file "phpthumb.class.php" on line 1140

resolvePath: iteration, path=/kunden/homepages/24/d147901974/htdocs/_feuerwehr/bildarchiv/2017/[20170422] Busfahrt Bamberg/FFW_Heubisch_Busfahrt_Bamberg_20170422_001.jpg, base path = /homepages/24/d147901974/htdocs/_feuerwehr in file "phpthumb.class.php" on line 1159

open_basedir: "" in file "phpthumb.class.php" on line 1126

resolvePath: stop at component 1 in file "phpthumb.class.php" on line 1175

resolvePath: stop at path=/kunden in file "phpthumb.class.php" on line 1178

resolvePath: no match, returning null in file "phpthumb.class.php" on line 1180

!$this->config_allow_src_above_docroot therefore setting "" (outside "/homepages/24/d147901974/htdocs/_feuerwehr") to null in file "phpthumb.class.php" on line 1344

$this->sourceFilename set to "" in file "phpthumb.class.php" on line 894

phpThumb() v1.7.14-201608101311
http://phpthumb.sourceforge.net

Error messages disabled.

edit phpThumb.config.php and (temporarily) set
$PHPTHUMB_CONFIG['disable_debug'] = false;
to view the details of this error in file "phpthumb.class.php" on line 4126

setCacheDirectory() starting with config_cache_directory = "" in file "phpthumb.class.php" on line 1005

$this->config_cache_directory () is not a directory in file "phpthumb.class.php" on line 1041

SetCacheFilename() failed because $this->config_cache_directory is empty in file "phpthumb.class.php" on line 3482

starting ExtractEXIFgetImageSize() in file "phpthumb.class.php" on line 3314

skipping getimagesize() because $this->sourceFilename is empty in file "phpthumb.class.php" on line 3326

getimagesize("") failed in file "phpthumb.class.php" on line 3357

$this->useRawIMoutput=true after checking $UnAllowedParameters in file "phpthumb.class.php" on line 1595

ImageMagickThumbnailToGD() aborting because $this->sourceFilename is empty in file "phpthumb.class.php" on line 1640

ImageMagickThumbnailToGD() failed in file "phpthumb.class.php" on line 3364

SetOrientationDependantWidthHeight() starting with ""x"" in file "phpthumb.class.php" on line 3293

SetOrientationDependantWidthHeight() setting w="70", h="70" in file "phpthumb.class.php" on line 3309

EXIF thumbnail extraction: (size=0; type=""; 0x0) in file "phpthumb.class.php" on line 3421

starting SourceImageToGD() in file "phpthumb.class.php" on line 3679

Not using EXIF thumbnail data because $this->exif_thumbnail_data is empty in file "phpthumb.class.php" on line 3751

$this->gdimg_source is still empty in file "phpthumb.class.php" on line 3803

ImageMagickThumbnailToGD() failed in file "phpthumb.class.php" on line 3805

phpThumb() v1.7.14-201608101311
http://phpthumb.sourceforge.net

Error messages disabled.

edit phpThumb.config.php and (temporarily) set
$PHPTHUMB_CONFIG['disable_debug'] = false;
to view the details of this error in file "phpthumb.class.php" on line 4126

SourceImageToGD() failed in file "phpthumb.class.php" on line 374

**Comment by JamesHeinrich** [comment]
Your problem is this:
```
!$this->config_allow_src_above_docroot therefore setting
"/kunden/homepages/24/d147901974/htdocs/_feuerwehr/bildarchiv/2017/[20170422] Busfahrt Bamberg/FFW_Heubisch_Busfahrt_Bamberg_20170422_001.jpg"
(outside "/homepages/24/d147901974/htdocs/_feuerwehr")
to null in file "phpthumb.class.php" on line 1344
```
I'm not sure where phpThumb lives on your server, but it's outside `/kunden/`
Please see phpThumb.config.php lines 46-49:
https://github.com/JamesHeinrich/phpThumb/blob/master/phpThumb.config.php.default#L46-L49
Note lines: `allow_src_above_docroot` and `allow_src_above_phpthumb` and possibly `additional_allowed_dirs`.

**Comment by ThiloL** [comment]
In my environment values from `phpThumb.config.php` are not used by `phpthumb.class.php`. That was the problem. I had to set `config_allow_src_above_docroot` in `phpthumb.class.php` as well.
