### ISSUE TITLE
Imagemagick cut off images when resizing

### ISSUE THREAD

**Issue by ricardovigatti** [JamesHeinrich/phpThumb#87]
When imagemagick is installed on the server, the resized image is being cut off. After digging into the problem, i realize that i can skip the problem commenting out the respective lines from phpthumb.class.php file:

https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php#L1775-L1779

    if (($wAll > 0) && ($hAll > 0)) {
        $commandline .= ' -crop '.phpthumb_functions::escapeshellarg_replacement($wAll.'x'.$hAll.'+0+0');
    } else {
        //$commandline .= ' -crop '.phpthumb_functions::escapeshellarg_replacement($side.'x'.$side.'+0+0');
    }

For now, i removed imagemagick from server. But i can't understand why i'm facing this issue. Anyone has a clue for this?

**Comment by JamesHeinrich** [comment]
That section of code only gets called if you're using the ZoomCrop parameter, and that's the whole point of that option: to zoom in and trim the edges of the image to exactly fill the specified width and height without distortion. If you don't want that, remove the &zc=1 from your call.
