### ISSUE TITLE
Generate PDF Thumbnail 

### ISSUE THREAD

**Issue by tasmer** [JamesHeinrich/phpThumb#89]
Hello,

I get a issue when I try to generate a PDF thumbnail, I get this error messages into the image thumbnail generate.

> ImageMagick and/or GhostScript are unavailable and phpThumb() does not support PDF source images without them

But ImageMagick and GhostScript are installed. I configured imagemagick_path with path to the conversion and I have the same error message.
`$PHPTHUMB_CONFIG['imagemagick_path'] = '/usr/local/bin/convert';`

> PHP 5.6.35
> PHPThumb 1.7.11-201108081537
> ImageMagick 7.0.7-4 Q16 x86_64 2017-10-02
> Ghostscript 9.21

**How I can debug and find the cause of issue ?**

This is my first request maybe I miss something.
Thanks you !

**Comment by JamesHeinrich** [comment]
First please update your phpThumb installation so I don't have to chase down bugs on a 6-year-old version.
If the problem still persists, please reopen this ticket.
