### ISSUE TITLE
Fatal error: Cannot declare class phpthumb_functions, because the name is already in use in \phpthumb\phpthumb.functions.php on line 12

### ISSUE THREAD

**Issue by arturmamedov** [JamesHeinrich/phpThumb#94]
After update to last version 1.7.14 i encounter this error on `PHP 7.2`
```
Fatal error: Cannot declare class phpthumb_functions, because the name is already in use in \phpthumb\phpthumb.functions.php on line 12
```

For this snippet of code: in `phpThumb.config.php`
```
define('phpThumbConfigFileVersion', '1.7.14');
ob_start();
    if ( ! file_exists(dirname(__FILE__).'/phpthumb.functions.php') || ! include_once(dirname(__FILE__).'/phpthumb.functions.php')) {
        ob_end_flush();
        die('failed to include_once(phpthumb.functions.php) - realpath="'.realpath(dirname(__FILE__).'/phpthumb.functions.php').'"');
    }
ob_end_clean();
```

If add a condition for class existance or remove this code, all work well. 
```
define('phpThumbConfigFileVersion', '1.7.14');
ob_start();
if( ! class_exists('phpthumb_functions')) {
    if ( ! file_exists(dirname(__FILE__).'/phpthumb.functions.php') || ! include_once(dirname(__FILE__).'/phpthumb.functions.php')) {
        ob_end_flush();
        die('failed to include_once(phpthumb.functions.php) - realpath="'.realpath(dirname(__FILE__).'/phpthumb.functions.php').'"');
    }
}
ob_end_clean();
```

__This is only my problem? Or i can make PR for others?__

**Comment by JamesHeinrich** [comment]
I'm not sure why it would give you an error, the whole purpose of _include_once_ is to prevent errors like that when an included file may have already been included elsewhere. Any insight as to how/where/why _phpthumb_functions_ is already defined without triggering the _include_once_ exclusion?

Nevertheless, I don't think there's any harm in wrapping that into a conditional, feel free to make a pull request and I'll merge it.

**Comment by ggppdk** [comment]
Are you testing in a windows or linux system

2 ways this may happen
- either the installation under some symbolic or hard link, and include_once sees 2 different file paths (why this happens ?)
- or could there be 2 installations of phpThumb in use ?

**Comment by arturmamedov** [comment]
Windows 10.

No i haven't 2 installation. 

it may be for the 2 different path, but i have 3 points in application where i call phpThumb for get me the cropped url one in View template, 2 in a PHP Trait for use it in Business logic, and third in Controller for format output of gallery, i use `CakePHP 3`. 
And i encure in Error when i'm use booth. But the inclusion, include only `include_once WWW_ROOT.'phpthumb'.DS.'phpThumb.config.php';` in same way in all 3 files and it include once the phpthumb_functions so it not for different paths, __can it be for the autoload?__

**Comment by JamesHeinrich** [comment]
Conditional added in https://github.com/JamesHeinrich/phpThumb/commit/3900a009c4cce3267868155c8164ef3734f2bd24
